var annotated_dup =
[
    [ "Domain_L_shaped", "namespace_domain___l__shaped.html", [
      [ "Function_NonZero_on_boundary_2", "class_domain___l__shaped_1_1_function___non_zero__on__boundary__2.html", "class_domain___l__shaped_1_1_function___non_zero__on__boundary__2" ]
    ] ],
    [ "Domain_square_01by01", "namespace_domain__square__01by01.html", [
      [ "Function_NonZero_on_boundary_1", "class_domain__square__01by01_1_1_function___non_zero__on__boundary__1.html", "class_domain__square__01by01_1_1_function___non_zero__on__boundary__1" ],
      [ "Function_Zero_on_boundary_1", "class_domain__square__01by01_1_1_function___zero__on__boundary__1.html", "class_domain__square__01by01_1_1_function___zero__on__boundary__1" ],
      [ "Function_Zero_on_boundary_2", "class_domain__square__01by01_1_1_function___zero__on__boundary__2.html", "class_domain__square__01by01_1_1_function___zero__on__boundary__2" ],
      [ "Function_Zero_on_boundary_3", "class_domain__square__01by01_1_1_function___zero__on__boundary__3.html", "class_domain__square__01by01_1_1_function___zero__on__boundary__3" ]
    ] ],
    [ "Domain_square_01by01_Mesh_Distorted", "namespace_domain__square__01by01___mesh___distorted.html", [
      [ "Function_Zero_on_boundary_Continuous0_NotC1_1", "class_domain__square__01by01___mesh___distorted_1_1_function___zero__on__boundary___continuous0___not_c1__1.html", "class_domain__square__01by01___mesh___distorted_1_1_function___zero__on__boundary___continuous0___not_c1__1" ]
    ] ],
    [ "Domain_square_01by01_Mesh_Straight", "namespace_domain__square__01by01___mesh___straight.html", [
      [ "Function_NonZero_on_boundary_Continuous0_1", "class_domain__square__01by01___mesh___straight_1_1_function___non_zero__on__boundary___continuous0__1.html", "class_domain__square__01by01___mesh___straight_1_1_function___non_zero__on__boundary___continuous0__1" ],
      [ "Function_Zero_on_boundary_Continuous1_1", "class_domain__square__01by01___mesh___straight_1_1_function___zero__on__boundary___continuous1__1.html", "class_domain__square__01by01___mesh___straight_1_1_function___zero__on__boundary___continuous1__1" ]
    ] ],
    [ "Domain_square_m05p05", "namespace_domain__square__m05p05.html", [
      [ "Function_Zero_on_boundary_4", "class_domain__square__m05p05_1_1_function___zero__on__boundary__4.html", "class_domain__square__m05p05_1_1_function___zero__on__boundary__4" ]
    ] ],
    [ "femus", "namespacefemus.html", [
      [ "ctrl", "namespacefemus_1_1ctrl.html", [
        [ "boundary_control_between_extreme", "namespacefemus_1_1ctrl_1_1boundary__control__between__extreme.html", [
          [ "cube", "namespacefemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube.html", [
            [ "List_of_Gamma_control_faces_Double", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___double.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Five", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___five.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___five" ],
            [ "List_of_Gamma_control_faces_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Single", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___single.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Six", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___six.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___six" ],
            [ "List_of_Gamma_control_faces_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___three" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_multiple__controls__and__hf246a5d96c0371b0dfd1a7f28d8926f1.html", null ]
          ] ],
          [ "square", "namespacefemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square.html", [
            [ "Boundary_Condition_control_between_extreme", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_boundary___condition__control__between__extreme.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_boundary___condition__control__between__extreme" ],
            [ "Double_controls_adjacent_in_front_linear", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_double__controls__adjacent__in__front__linear.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_double__controls__adjacent__in__front__linear" ],
            [ "List_of_Gamma_control_faces_Double", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___double.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_One_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___three" ],
            [ "List_of_Gamma_control_faces_Four_One_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_Four_Two_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two___three" ],
            [ "List_of_Gamma_control_faces_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___three" ],
            [ "List_of_Gamma_control_faces_One_Four_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___two" ],
            [ "List_of_Gamma_control_faces_One_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___four" ],
            [ "List_of_Gamma_control_faces_One_Three_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___two" ],
            [ "List_of_Gamma_control_faces_One_Three_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__controb8d795ffe0db3c54a4be746b7d52b5a9.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__controb8d795ffe0db3c54a4be746b7d52b5a9" ],
            [ "List_of_Gamma_control_faces_One_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Quadruple", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___quadruple.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___quadruple" ],
            [ "List_of_Gamma_control_faces_Single", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___single.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_One_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___four" ],
            [ "List_of_Gamma_control_faces_Three_One_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___two" ],
            [ "List_of_Gamma_control_faces_Three_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Three_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___four" ],
            [ "List_of_Gamma_control_faces_Three_Two_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___one" ],
            [ "List_of_Gamma_control_faces_Triple", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___triple.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___triple" ],
            [ "List_of_Gamma_control_faces_Two", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_Four_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___one" ],
            [ "List_of_Gamma_control_faces_Two_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___three" ],
            [ "List_of_Gamma_control_faces_Two_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three" ],
            [ "List_of_Gamma_control_faces_Two_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___four" ],
            [ "List_of_Gamma_control_faces_Two_Three_One", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___one.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___one" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__and_b461cb5d81624a4feb17a56b9e0453e1.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__and_b461cb5d81624a4feb17a56b9e0453e1" ],
            [ "Multiple_controls_in_front_constant", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__in__front__constant.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__in__front__constant" ],
            [ "Single_control_in_front_linear", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_single__control__in__front__linear.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_single__control__in__front__linear" ],
            [ "Triple_controls_adjacent_in_front_linear", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_triple__controls__adjacent__in__front__linear.html", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_triple__controls__adjacent__in__front__linear" ]
          ] ]
        ] ],
        [ "boundary_control_full_face", "namespacefemus_1_1ctrl_1_1boundary__control__full__face.html", [
          [ "cube", "namespacefemus_1_1ctrl_1_1boundary__control__full__face_1_1cube.html", [
            [ "List_of_Gamma_control_faces_Double", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___double.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Five", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___five.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___five" ],
            [ "List_of_Gamma_control_faces_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Single", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___single.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Six", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___six.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___six" ],
            [ "List_of_Gamma_control_faces_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___three" ]
          ] ],
          [ "square", "namespacefemus_1_1ctrl_1_1boundary__control__full__face_1_1square.html", [
            [ "Boundary_Condition_control_full_face", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_boundary___condition__control__full__face.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_boundary___condition__control__full__face" ],
            [ "Double_controls_adjacent_in_front_linear", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_double__controls__adjacent__in__front__linear.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_double__controls__adjacent__in__front__linear" ],
            [ "List_of_Gamma_control_faces_Double", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___double.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_One_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___three" ],
            [ "List_of_Gamma_control_faces_Four_One_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_Four_Two_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two___three" ],
            [ "List_of_Gamma_control_faces_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___three" ],
            [ "List_of_Gamma_control_faces_One_Four_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___two" ],
            [ "List_of_Gamma_control_faces_One_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___four" ],
            [ "List_of_Gamma_control_faces_One_Three_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two" ],
            [ "List_of_Gamma_control_faces_One_Three_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two___four" ],
            [ "List_of_Gamma_control_faces_One_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Quadruple", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___quadruple.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___quadruple" ],
            [ "List_of_Gamma_control_faces_Single", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___single.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_One_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___four" ],
            [ "List_of_Gamma_control_faces_Three_One_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___two" ],
            [ "List_of_Gamma_control_faces_Three_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Three_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___four" ],
            [ "List_of_Gamma_control_faces_Three_Two_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___one" ],
            [ "List_of_Gamma_control_faces_Triple", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___triple.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___triple" ],
            [ "List_of_Gamma_control_faces_Two", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_Four_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___one" ],
            [ "List_of_Gamma_control_faces_Two_Four_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___three" ],
            [ "List_of_Gamma_control_faces_Two_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three" ],
            [ "List_of_Gamma_control_faces_Two_Three_Four", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___four.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___four" ],
            [ "List_of_Gamma_control_faces_Two_Three_One", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___one.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___one" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__and__homogeneous__boundary__conditions.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__and__homogeneous__boundary__conditions" ],
            [ "Multiple_controls_in_front_constant", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__in__front__constant.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__in__front__constant" ],
            [ "Single_control_in_front_linear", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_single__control__in__front__linear.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_single__control__in__front__linear" ],
            [ "Triple_controls_adjacent_in_front_linear", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_triple__controls__adjacent__in__front__linear.html", "classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_triple__controls__adjacent__in__front__linear" ]
          ] ]
        ] ],
        [ "cube", "namespacefemus_1_1ctrl_1_1cube.html", [
          [ "cost_functional_without_regularization", "classfemus_1_1ctrl_1_1cube_1_1cost__functional__without__regularization.html", null ]
        ] ],
        [ "square", "namespacefemus_1_1ctrl_1_1square.html", [
          [ "cost_functional_without_regularization", "classfemus_1_1ctrl_1_1square_1_1cost__functional__without__regularization.html", null ]
        ] ],
        [ "square_or_cube", "namespacefemus_1_1ctrl_1_1square__or__cube.html", [
          [ "Boundary_Condition", "classfemus_1_1ctrl_1_1square__or__cube_1_1_boundary___condition.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1_boundary___condition" ],
          [ "cost_functional_without_regularization", "classfemus_1_1ctrl_1_1square__or__cube_1_1cost__functional__without__regularization.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1cost__functional__without__regularization" ],
          [ "Domain_elements_containing_Gamma_control", "classfemus_1_1ctrl_1_1square__or__cube_1_1_domain__elements__containing___gamma__control.html", null ],
          [ "lifting_external", "classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__external.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__external" ],
          [ "lifting_internal", "classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__internal.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__internal" ],
          [ "List_of_faces", "classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of__faces.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of__faces" ],
          [ "List_of_Gamma_control_faces", "classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of___gamma__control__faces.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of___gamma__control__faces" ],
          [ "mixed_state_or_ctrl_inequality", "classfemus_1_1ctrl_1_1square__or__cube_1_1mixed__state__or__ctrl__inequality.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1mixed__state__or__ctrl__inequality" ],
          [ "pure_boundary", "classfemus_1_1ctrl_1_1square__or__cube_1_1pure__boundary.html", "classfemus_1_1ctrl_1_1square__or__cube_1_1pure__boundary" ]
        ] ],
        [ "cost_functional", "classfemus_1_1ctrl_1_1cost__functional.html", "classfemus_1_1ctrl_1_1cost__functional" ],
        [ "cost_functional_without_regularization", "classfemus_1_1ctrl_1_1cost__functional__without__regularization.html", null ],
        [ "Domain_of_PDE", "classfemus_1_1ctrl_1_1_domain__of___p_d_e.html", "classfemus_1_1ctrl_1_1_domain__of___p_d_e" ],
        [ "Gamma_control_equation_fractional_sobolev_differentiability_index", "classfemus_1_1ctrl_1_1_gamma__control__equation__fractional__sobolev__differentiability__index.html", "classfemus_1_1ctrl_1_1_gamma__control__equation__fractional__sobolev__differentiability__index" ],
        [ "Gamma_control_equation_integer_sobolev_differentiability_index", "classfemus_1_1ctrl_1_1_gamma__control__equation__integer__sobolev__differentiability__index.html", "classfemus_1_1ctrl_1_1_gamma__control__equation__integer__sobolev__differentiability__index" ],
        [ "mixed_state_or_ctrl_inequality", "classfemus_1_1ctrl_1_1mixed__state__or__ctrl__inequality.html", "classfemus_1_1ctrl_1_1mixed__state__or__ctrl__inequality" ]
      ] ],
      [ "elliptic", "namespacefemus_1_1elliptic.html", [
        [ "lifting_external", "classfemus_1_1elliptic_1_1lifting__external.html", "classfemus_1_1elliptic_1_1lifting__external" ],
        [ "lifting_internal", "classfemus_1_1elliptic_1_1lifting__internal.html", "classfemus_1_1elliptic_1_1lifting__internal" ],
        [ "pure_boundary", "classfemus_1_1elliptic_1_1pure__boundary.html", "classfemus_1_1elliptic_1_1pure__boundary" ]
      ] ],
      [ "Math", "namespacefemus_1_1_math.html", [
        [ "Function", "classfemus_1_1_math_1_1_function.html", "classfemus_1_1_math_1_1_function" ]
      ] ],
      [ "navier_stokes", "namespacefemus_1_1navier__stokes.html", [
        [ "lifting_internal", "classfemus_1_1navier__stokes_1_1lifting__internal.html", "classfemus_1_1navier__stokes_1_1lifting__internal" ],
        [ "pure_boundary", "classfemus_1_1navier__stokes_1_1pure__boundary.html", "classfemus_1_1navier__stokes_1_1pure__boundary" ]
      ] ],
      [ "Parallel", "namespacefemus_1_1_parallel.html", [
        [ "data_type", "namespacefemus_1_1_parallel.html#structfemus_1_1_parallel_1_1data__type", null ],
        [ "DataType", "classfemus_1_1_parallel_1_1_data_type.html", "classfemus_1_1_parallel_1_1_data_type" ],
        [ "request", "namespacefemus_1_1_parallel.html#structfemus_1_1_parallel_1_1request", null ],
        [ "Request", "classfemus_1_1_parallel_1_1_request.html", "classfemus_1_1_parallel_1_1_request" ],
        [ "status", "namespacefemus_1_1_parallel.html#structfemus_1_1_parallel_1_1status", null ],
        [ "Status", "classfemus_1_1_parallel_1_1_status.html", "classfemus_1_1_parallel_1_1_status" ]
      ] ],
      [ "app_specifics", "classfemus_1_1app__specifics.html", "classfemus_1_1app__specifics" ],
      [ "assemble_jacobian", "classfemus_1_1assemble__jacobian.html", "classfemus_1_1assemble__jacobian" ],
      [ "basis", "classfemus_1_1basis.html", "classfemus_1_1basis" ],
      [ "BoundaryConditions", "classfemus_1_1_boundary_conditions.html", "classfemus_1_1_boundary_conditions" ],
      [ "Box", "classfemus_1_1_box.html", "classfemus_1_1_box" ],
      [ "CurrentElem", "classfemus_1_1_current_elem.html", "classfemus_1_1_current_elem" ],
      [ "CurrentQuantity", "classfemus_1_1_current_quantity.html", "classfemus_1_1_current_quantity" ],
      [ "DenseMatrix", "classfemus_1_1_dense_matrix.html", "classfemus_1_1_dense_matrix" ],
      [ "DenseMatrixBase", "classfemus_1_1_dense_matrix_base.html", "classfemus_1_1_dense_matrix_base" ],
      [ "DenseSubMatrix", "classfemus_1_1_dense_sub_matrix.html", "classfemus_1_1_dense_sub_matrix" ],
      [ "DenseSubVector", "classfemus_1_1_dense_sub_vector.html", "classfemus_1_1_dense_sub_vector" ],
      [ "DenseVector", "classfemus_1_1_dense_vector.html", "classfemus_1_1_dense_vector" ],
      [ "DenseVectorBase", "classfemus_1_1_dense_vector_base.html", "classfemus_1_1_dense_vector_base" ],
      [ "DofMap", "classfemus_1_1_dof_map.html", "classfemus_1_1_dof_map" ],
      [ "Domain", "classfemus_1_1_domain.html", "classfemus_1_1_domain" ],
      [ "elem", "classfemus_1_1elem.html", "classfemus_1_1elem" ],
      [ "elem_type", "classfemus_1_1elem__type.html", "classfemus_1_1elem__type" ],
      [ "elem_type_1D", "classfemus_1_1elem__type__1_d.html", "classfemus_1_1elem__type__1_d" ],
      [ "elem_type_2D", "classfemus_1_1elem__type__2_d.html", "classfemus_1_1elem__type__2_d" ],
      [ "elem_type_3D", "classfemus_1_1elem__type__3_d.html", "classfemus_1_1elem__type__3_d" ],
      [ "elem_type_templ", "classfemus_1_1elem__type__templ.html", "classfemus_1_1elem__type__templ" ],
      [ "elem_type_templ< type, type_mov, 1, 3 >", "classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_011_00_013_01_4.html", "classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_011_00_013_01_4" ],
      [ "elem_type_templ< type, type_mov, 2, 3 >", "classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_012_00_013_01_4.html", "classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_012_00_013_01_4" ],
      [ "elem_type_templ< type, type_mov, 3, 3 >", "classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_013_00_013_01_4.html", "classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_013_00_013_01_4" ],
      [ "elem_type_templ_base", "classfemus_1_1elem__type__templ__base.html", "classfemus_1_1elem__type__templ__base" ],
      [ "ElementJacRes", "classfemus_1_1_element_jac_res.html", "classfemus_1_1_element_jac_res" ],
      [ "ElemStoBase", "classfemus_1_1_elem_sto_base.html", "classfemus_1_1_elem_sto_base" ],
      [ "ElemStoBdry", "classfemus_1_1_elem_sto_bdry.html", "classfemus_1_1_elem_sto_bdry" ],
      [ "ElemStoVol", "classfemus_1_1_elem_sto_vol.html", "classfemus_1_1_elem_sto_vol" ],
      [ "ExplicitSystem", "classfemus_1_1_explicit_system.html", "classfemus_1_1_explicit_system" ],
      [ "FE_convergence", "classfemus_1_1_f_e__convergence.html", "classfemus_1_1_f_e__convergence" ],
      [ "FemusInit", "classfemus_1_1_femus_init.html", "classfemus_1_1_femus_init" ],
      [ "FemusInputParser", "classfemus_1_1_femus_input_parser.html", "classfemus_1_1_femus_input_parser" ],
      [ "FieldSplitTree", "classfemus_1_1_field_split_tree.html", "classfemus_1_1_field_split_tree" ],
      [ "Files", "classfemus_1_1_files.html", "classfemus_1_1_files" ],
      [ "Fluid", "classfemus_1_1_fluid.html", "classfemus_1_1_fluid" ],
      [ "FunctionBase", "classfemus_1_1_function_base.html", "classfemus_1_1_function_base" ],
      [ "GambitIO", "classfemus_1_1_gambit_i_o.html", "classfemus_1_1_gambit_i_o" ],
      [ "Gauss", "classfemus_1_1_gauss.html", "classfemus_1_1_gauss" ],
      [ "GenCase", "classfemus_1_1_gen_case.html", "classfemus_1_1_gen_case" ],
      [ "GeomElemBase", "classfemus_1_1_geom_elem_base.html", "classfemus_1_1_geom_elem_base" ],
      [ "GeomElemEdge2", "classfemus_1_1_geom_elem_edge2.html", "classfemus_1_1_geom_elem_edge2" ],
      [ "GeomElemEdge3", "classfemus_1_1_geom_elem_edge3.html", "classfemus_1_1_geom_elem_edge3" ],
      [ "GeomElemHex27", "classfemus_1_1_geom_elem_hex27.html", "classfemus_1_1_geom_elem_hex27" ],
      [ "GeomElemHex8", "classfemus_1_1_geom_elem_hex8.html", "classfemus_1_1_geom_elem_hex8" ],
      [ "GeomElemQuad4", "classfemus_1_1_geom_elem_quad4.html", "classfemus_1_1_geom_elem_quad4" ],
      [ "GeomElemQuad9", "classfemus_1_1_geom_elem_quad9.html", "classfemus_1_1_geom_elem_quad9" ],
      [ "GeomElemTet10", "classfemus_1_1_geom_elem_tet10.html", "classfemus_1_1_geom_elem_tet10" ],
      [ "GeomElemTet4", "classfemus_1_1_geom_elem_tet4.html", "classfemus_1_1_geom_elem_tet4" ],
      [ "GeomElemTri3", "classfemus_1_1_geom_elem_tri3.html", "classfemus_1_1_geom_elem_tri3" ],
      [ "GeomElemTri6", "classfemus_1_1_geom_elem_tri6.html", "classfemus_1_1_geom_elem_tri6" ],
      [ "GeomElemTri7", "classfemus_1_1_geom_elem_tri7.html", "classfemus_1_1_geom_elem_tri7" ],
      [ "GMVWriter", "classfemus_1_1_g_m_v_writer.html", "classfemus_1_1_g_m_v_writer" ],
      [ "Graph", "classfemus_1_1_graph.html", "classfemus_1_1_graph" ],
      [ "Gravity", "classfemus_1_1_gravity.html", "classfemus_1_1_gravity" ],
      [ "hex0", "classfemus_1_1hex0.html", "classfemus_1_1hex0" ],
      [ "hex_const", "classfemus_1_1hex__const.html", "classfemus_1_1hex__const" ],
      [ "hex_gauss", "classfemus_1_1hex__gauss.html", "classfemus_1_1hex__gauss" ],
      [ "hex_lag", "classfemus_1_1hex__lag.html", "classfemus_1_1hex__lag" ],
      [ "HexBiquadratic", "classfemus_1_1_hex_biquadratic.html", "classfemus_1_1_hex_biquadratic" ],
      [ "HexLinear", "classfemus_1_1_hex_linear.html", "classfemus_1_1_hex_linear" ],
      [ "hexpwLinear", "classfemus_1_1hexpw_linear.html", "classfemus_1_1hexpw_linear" ],
      [ "HexQuadratic", "classfemus_1_1_hex_quadratic.html", "classfemus_1_1_hex_quadratic" ],
      [ "HtmlInputParser", "classfemus_1_1_html_input_parser.html", "classfemus_1_1_html_input_parser" ],
      [ "ImplicitRungeKuttaSystem", "classfemus_1_1_implicit_runge_kutta_system.html", "classfemus_1_1_implicit_runge_kutta_system" ],
      [ "ImplicitSystem", "classfemus_1_1_implicit_system.html", "classfemus_1_1_implicit_system" ],
      [ "InputParser", "classfemus_1_1_input_parser.html", "classfemus_1_1_input_parser" ],
      [ "JsonInputParser", "classfemus_1_1_json_input_parser.html", "classfemus_1_1_json_input_parser" ],
      [ "lifting_external", "classfemus_1_1lifting__external.html", "classfemus_1_1lifting__external" ],
      [ "lifting_internal", "classfemus_1_1lifting__internal.html", "classfemus_1_1lifting__internal" ],
      [ "Line", "classfemus_1_1_line.html", "classfemus_1_1_line" ],
      [ "line0", "classfemus_1_1line0.html", "classfemus_1_1line0" ],
      [ "line_const", "classfemus_1_1line__const.html", "classfemus_1_1line__const" ],
      [ "line_gauss", "classfemus_1_1line__gauss.html", "classfemus_1_1line__gauss" ],
      [ "line_lag", "classfemus_1_1line__lag.html", "classfemus_1_1line__lag" ],
      [ "LinearEquation", "classfemus_1_1_linear_equation.html", "classfemus_1_1_linear_equation" ],
      [ "LinearEquationSolver", "classfemus_1_1_linear_equation_solver.html", "classfemus_1_1_linear_equation_solver" ],
      [ "LinearImplicitSystem", "classfemus_1_1_linear_implicit_system.html", "classfemus_1_1_linear_implicit_system" ],
      [ "LineBiquadratic", "classfemus_1_1_line_biquadratic.html", "classfemus_1_1_line_biquadratic" ],
      [ "LineLinear", "classfemus_1_1_line_linear.html", "classfemus_1_1_line_linear" ],
      [ "linepwLinear", "classfemus_1_1linepw_linear.html", "classfemus_1_1linepw_linear" ],
      [ "Marker", "classfemus_1_1_marker.html", "classfemus_1_1_marker" ],
      [ "Material", "classfemus_1_1_material.html", "classfemus_1_1_material" ],
      [ "Mesh", "classfemus_1_1_mesh.html", "classfemus_1_1_mesh" ],
      [ "MeshASMPartitioning", "classfemus_1_1_mesh_a_s_m_partitioning.html", "classfemus_1_1_mesh_a_s_m_partitioning" ],
      [ "MeshInput", "classfemus_1_1_mesh_input.html", "classfemus_1_1_mesh_input" ],
      [ "MeshMetisPartitioning", "classfemus_1_1_mesh_metis_partitioning.html", "classfemus_1_1_mesh_metis_partitioning" ],
      [ "MeshPartitioning", "classfemus_1_1_mesh_partitioning.html", "classfemus_1_1_mesh_partitioning" ],
      [ "MeshRefinement", "classfemus_1_1_mesh_refinement.html", "classfemus_1_1_mesh_refinement" ],
      [ "MonolithicFSINonLinearImplicitSystem", "classfemus_1_1_monolithic_f_s_i_non_linear_implicit_system.html", "classfemus_1_1_monolithic_f_s_i_non_linear_implicit_system" ],
      [ "MultiLevelMesh", "classfemus_1_1_multi_level_mesh.html", "classfemus_1_1_multi_level_mesh" ],
      [ "MultiLevelMeshTwo", "classfemus_1_1_multi_level_mesh_two.html", "classfemus_1_1_multi_level_mesh_two" ],
      [ "MultiLevelProblem", "classfemus_1_1_multi_level_problem.html", "classfemus_1_1_multi_level_problem" ],
      [ "MultiLevelSolution", "classfemus_1_1_multi_level_solution.html", "classfemus_1_1_multi_level_solution" ],
      [ "MyMatrix", "classfemus_1_1_my_matrix.html", "classfemus_1_1_my_matrix" ],
      [ "MyVector", "classfemus_1_1_my_vector.html", "classfemus_1_1_my_vector" ],
      [ "NewmarkTransientSystem", "classfemus_1_1_newmark_transient_system.html", "classfemus_1_1_newmark_transient_system" ],
      [ "NodeSto", "classfemus_1_1_node_sto.html", "classfemus_1_1_node_sto" ],
      [ "NonLinearImplicitSystem", "classfemus_1_1_non_linear_implicit_system.html", "classfemus_1_1_non_linear_implicit_system" ],
      [ "NonLinearImplicitSystemWithPrimalDualActiveSetMethod", "classfemus_1_1_non_linear_implicit_system_with_primal_dual_active_set_method.html", "classfemus_1_1_non_linear_implicit_system_with_primal_dual_active_set_method" ],
      [ "NumericVector", "classfemus_1_1_numeric_vector.html", "classfemus_1_1_numeric_vector" ],
      [ "OptLoop", "classfemus_1_1_opt_loop.html", "classfemus_1_1_opt_loop" ],
      [ "ParallelObject", "classfemus_1_1_parallel_object.html", "classfemus_1_1_parallel_object" ],
      [ "Parameter", "classfemus_1_1_parameter.html", "classfemus_1_1_parameter" ],
      [ "Parameters", "classfemus_1_1_parameters.html", "classfemus_1_1_parameters" ],
      [ "ParsedFunction", "classfemus_1_1_parsed_function.html", "classfemus_1_1_parsed_function" ],
      [ "Phi", "classfemus_1_1_phi.html", "classfemus_1_1_phi" ],
      [ "point_gauss", "classfemus_1_1point__gauss.html", "classfemus_1_1point__gauss" ],
      [ "poisson_equation", "classfemus_1_1poisson__equation.html", "classfemus_1_1poisson__equation" ],
      [ "Preconditioner", "classfemus_1_1_preconditioner.html", "classfemus_1_1_preconditioner" ],
      [ "pure_boundary", "classfemus_1_1pure__boundary.html", "classfemus_1_1pure__boundary" ],
      [ "quad0", "classfemus_1_1quad0.html", "classfemus_1_1quad0" ],
      [ "quad_const", "classfemus_1_1quad__const.html", "classfemus_1_1quad__const" ],
      [ "quad_gauss", "classfemus_1_1quad__gauss.html", "classfemus_1_1quad__gauss" ],
      [ "quad_lag", "classfemus_1_1quad__lag.html", "classfemus_1_1quad__lag" ],
      [ "QuadBiquadratic", "classfemus_1_1_quad_biquadratic.html", "classfemus_1_1_quad_biquadratic" ],
      [ "QuadLinear", "classfemus_1_1_quad_linear.html", "classfemus_1_1_quad_linear" ],
      [ "quadpwLinear", "classfemus_1_1quadpw_linear.html", "classfemus_1_1quadpw_linear" ],
      [ "QuadQuadratic", "classfemus_1_1_quad_quadratic.html", "classfemus_1_1_quad_quadratic" ],
      [ "Quantity", "classfemus_1_1_quantity.html", "classfemus_1_1_quantity" ],
      [ "QuantityMap", "classfemus_1_1_quantity_map.html", "classfemus_1_1_quantity_map" ],
      [ "Solid", "classfemus_1_1_solid.html", "classfemus_1_1_solid" ],
      [ "Solution", "classfemus_1_1_solution.html", "classfemus_1_1_solution" ],
      [ "Solution_generation_single_level", "classfemus_1_1_solution__generation__single__level.html", "classfemus_1_1_solution__generation__single__level" ],
      [ "sparseGrid", "classfemus_1_1sparse_grid.html", "classfemus_1_1sparse_grid" ],
      [ "SparseMatrix", "classfemus_1_1_sparse_matrix.html", "classfemus_1_1_sparse_matrix" ],
      [ "System", "classfemus_1_1_system.html", "classfemus_1_1_system" ],
      [ "SystemTwo", "classfemus_1_1_system_two.html", "classfemus_1_1_system_two" ],
      [ "tet0", "classfemus_1_1tet0.html", "classfemus_1_1tet0" ],
      [ "tet_const", "classfemus_1_1tet__const.html", "classfemus_1_1tet__const" ],
      [ "tet_gauss", "classfemus_1_1tet__gauss.html", "classfemus_1_1tet__gauss" ],
      [ "tet_lag", "classfemus_1_1tet__lag.html", "classfemus_1_1tet__lag" ],
      [ "TetBiquadratic", "classfemus_1_1_tet_biquadratic.html", "classfemus_1_1_tet_biquadratic" ],
      [ "TetLinear", "classfemus_1_1_tet_linear.html", "classfemus_1_1_tet_linear" ],
      [ "tetpwLinear", "classfemus_1_1tetpw_linear.html", "classfemus_1_1tetpw_linear" ],
      [ "TetQuadratic", "classfemus_1_1_tet_quadratic.html", "classfemus_1_1_tet_quadratic" ],
      [ "TimeLoop", "classfemus_1_1_time_loop.html", "classfemus_1_1_time_loop" ],
      [ "TransientSystem", "classfemus_1_1_transient_system.html", "classfemus_1_1_transient_system" ],
      [ "tri0", "classfemus_1_1tri0.html", "classfemus_1_1tri0" ],
      [ "tri_const", "classfemus_1_1tri__const.html", "classfemus_1_1tri__const" ],
      [ "tri_gauss", "classfemus_1_1tri__gauss.html", "classfemus_1_1tri__gauss" ],
      [ "tri_lag", "classfemus_1_1tri__lag.html", "classfemus_1_1tri__lag" ],
      [ "TriBiquadratic", "classfemus_1_1_tri_biquadratic.html", "classfemus_1_1_tri_biquadratic" ],
      [ "TriLinear", "classfemus_1_1_tri_linear.html", "classfemus_1_1_tri_linear" ],
      [ "tripwLinear", "classfemus_1_1tripw_linear.html", "classfemus_1_1tripw_linear" ],
      [ "TriQuadratic", "classfemus_1_1_tri_quadratic.html", "classfemus_1_1_tri_quadratic" ],
      [ "Unknown", "namespacefemus.html#classfemus_1_1_unknown", "namespacefemus_classfemus_1_1_unknown_dup" ],
      [ "UnknownLocal", "classfemus_1_1_unknown_local.html", "classfemus_1_1_unknown_local" ],
      [ "uq", "classfemus_1_1uq.html", "classfemus_1_1uq" ],
      [ "VTKWriter", "classfemus_1_1_v_t_k_writer.html", "classfemus_1_1_v_t_k_writer" ],
      [ "wedge0", "classfemus_1_1wedge0.html", "classfemus_1_1wedge0" ],
      [ "wedge_const", "classfemus_1_1wedge__const.html", "classfemus_1_1wedge__const" ],
      [ "wedge_gauss", "classfemus_1_1wedge__gauss.html", "classfemus_1_1wedge__gauss" ],
      [ "wedge_lag", "classfemus_1_1wedge__lag.html", "classfemus_1_1wedge__lag" ],
      [ "WedgeBiquadratic", "classfemus_1_1_wedge_biquadratic.html", "classfemus_1_1_wedge_biquadratic" ],
      [ "WedgeLinear", "classfemus_1_1_wedge_linear.html", "classfemus_1_1_wedge_linear" ],
      [ "wedgepwLinear", "classfemus_1_1wedgepw_linear.html", "classfemus_1_1wedgepw_linear" ],
      [ "WedgeQuadratic", "classfemus_1_1_wedge_quadratic.html", "classfemus_1_1_wedge_quadratic" ],
      [ "Writer", "classfemus_1_1_writer.html", "classfemus_1_1_writer" ]
    ] ],
    [ "array", "classarray.html", "classarray" ],
    [ "GMPM", "class_g_m_p_m.html", "class_g_m_p_m" ],
    [ "MagnFieldExtLagMult", "class_magn_field_ext_lag_mult.html", "class_magn_field_ext_lag_mult" ],
    [ "MagnFieldExtX", "class_magn_field_ext_x.html", "class_magn_field_ext_x" ],
    [ "MagnFieldExtY", "class_magn_field_ext_y.html", "class_magn_field_ext_y" ],
    [ "MagnFieldExtZ", "class_magn_field_ext_z.html", "class_magn_field_ext_z" ],
    [ "MagnFieldHomAdjX", "class_magn_field_hom_adj_x.html", "class_magn_field_hom_adj_x" ],
    [ "MagnFieldHomAdjY", "class_magn_field_hom_adj_y.html", "class_magn_field_hom_adj_y" ],
    [ "MagnFieldHomAdjZ", "class_magn_field_hom_adj_z.html", "class_magn_field_hom_adj_z" ],
    [ "MagnFieldHomLagMult", "class_magn_field_hom_lag_mult.html", "class_magn_field_hom_lag_mult" ],
    [ "MagnFieldHomLagMultAdj", "class_magn_field_hom_lag_mult_adj.html", "class_magn_field_hom_lag_mult_adj" ],
    [ "MagnFieldHomX", "class_magn_field_hom_x.html", "class_magn_field_hom_x" ],
    [ "MagnFieldHomY", "class_magn_field_hom_y.html", "class_magn_field_hom_y" ],
    [ "MagnFieldHomZ", "class_magn_field_hom_z.html", "class_magn_field_hom_z" ],
    [ "Pressure", "class_pressure.html", "class_pressure" ],
    [ "PressureAdj", "class_pressure_adj.html", "class_pressure_adj" ],
    [ "Singularity", "class_singularity.html", "class_singularity" ],
    [ "Solution_generation_1", "class_solution__generation__1.html", "class_solution__generation__1" ],
    [ "Sphere", "class_sphere.html", "class_sphere" ],
    [ "Stokes", "_p_c_field_split_2ex6_2ex6_8cpp.html#struct_stokes", "_p_c_field_split_2ex6_2ex6_8cpp_struct_stokes" ],
    [ "TempAdj", "class_temp_adj.html", "class_temp_adj" ],
    [ "Temperature", "class_temperature.html", "class_temperature" ],
    [ "TempLift", "class_temp_lift.html", "class_temp_lift" ],
    [ "VelocityAdjX", "class_velocity_adj_x.html", "class_velocity_adj_x" ],
    [ "VelocityAdjY", "class_velocity_adj_y.html", "class_velocity_adj_y" ],
    [ "VelocityAdjZ", "class_velocity_adj_z.html", "class_velocity_adj_z" ],
    [ "VelocityX", "class_velocity_x.html", "class_velocity_x" ],
    [ "VelocityY", "class_velocity_y.html", "class_velocity_y" ],
    [ "VelocityZ", "class_velocity_z.html", "class_velocity_z" ],
    [ "WindowFunction", "class_window_function.html", "class_window_function" ],
    [ "Zero", "class_zero.html", "class_zero" ]
];