var annotated_dup =
[
    [ "Domain_L_shaped", "d1/df9/namespaceDomain__L__shaped.html", [
      [ "Function_NonZero_on_boundary_2", "d7/dd9/classDomain__L__shaped_1_1Function__NonZero__on__boundary__2.html", "d7/dd9/classDomain__L__shaped_1_1Function__NonZero__on__boundary__2" ]
    ] ],
    [ "Domain_square_01by01", "d3/d7c/namespaceDomain__square__01by01.html", [
      [ "Function_NonZero_on_boundary_1", "d6/d92/classDomain__square__01by01_1_1Function__NonZero__on__boundary__1.html", "d6/d92/classDomain__square__01by01_1_1Function__NonZero__on__boundary__1" ],
      [ "Function_Zero_on_boundary_1", "d8/def/classDomain__square__01by01_1_1Function__Zero__on__boundary__1.html", "d8/def/classDomain__square__01by01_1_1Function__Zero__on__boundary__1" ],
      [ "Function_Zero_on_boundary_2", "de/d85/classDomain__square__01by01_1_1Function__Zero__on__boundary__2.html", "de/d85/classDomain__square__01by01_1_1Function__Zero__on__boundary__2" ],
      [ "Function_Zero_on_boundary_3", "dd/d63/classDomain__square__01by01_1_1Function__Zero__on__boundary__3.html", "dd/d63/classDomain__square__01by01_1_1Function__Zero__on__boundary__3" ]
    ] ],
    [ "Domain_square_01by01_Mesh_Distorted", "d3/d91/namespaceDomain__square__01by01__Mesh__Distorted.html", [
      [ "Function_Zero_on_boundary_Continuous0_NotC1_1", "d3/d7d/classDomain__square__01by01__Mesh__Distorted_1_1Function__Zero__on__boundary__Continuous0__NotC1__1.html", "d3/d7d/classDomain__square__01by01__Mesh__Distorted_1_1Function__Zero__on__boundary__Continuous0__NotC1__1" ]
    ] ],
    [ "Domain_square_01by01_Mesh_Straight", "dc/dee/namespaceDomain__square__01by01__Mesh__Straight.html", [
      [ "Function_NonZero_on_boundary_Continuous0_1", "df/d25/classDomain__square__01by01__Mesh__Straight_1_1Function__NonZero__on__boundary__Continuous0__1.html", "df/d25/classDomain__square__01by01__Mesh__Straight_1_1Function__NonZero__on__boundary__Continuous0__1" ],
      [ "Function_Zero_on_boundary_Continuous1_1", "d7/deb/classDomain__square__01by01__Mesh__Straight_1_1Function__Zero__on__boundary__Continuous1__1.html", "d7/deb/classDomain__square__01by01__Mesh__Straight_1_1Function__Zero__on__boundary__Continuous1__1" ]
    ] ],
    [ "Domain_square_m05p05", "d4/d6f/namespaceDomain__square__m05p05.html", [
      [ "Function_Zero_on_boundary_4", "da/d4f/classDomain__square__m05p05_1_1Function__Zero__on__boundary__4.html", "da/d4f/classDomain__square__m05p05_1_1Function__Zero__on__boundary__4" ]
    ] ],
    [ "femus", "d8/dea/namespacefemus.html", [
      [ "ctrl", "dc/dbd/namespacefemus_1_1ctrl.html", [
        [ "boundary_control_between_extreme", "dd/d57/namespacefemus_1_1ctrl_1_1boundary__control__between__extreme.html", [
          [ "cube", "d4/da0/namespacefemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube.html", [
            [ "List_of_Gamma_control_faces_Single", "d7/d9b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Single.html", "d7/d9b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Single" ],
            [ "List_of_Gamma_control_faces_One", "d7/d36/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One.html", "d7/d36/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One" ],
            [ "List_of_Gamma_control_faces_Two", "d0/d7e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two.html", "d0/d7e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two" ],
            [ "List_of_Gamma_control_faces_Three", "dc/d02/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three.html", "dc/d02/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three" ],
            [ "List_of_Gamma_control_faces_Four", "db/d97/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four.html", "db/d97/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four" ],
            [ "List_of_Gamma_control_faces_Five", "d7/d50/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Five.html", "d7/d50/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Five" ],
            [ "List_of_Gamma_control_faces_Six", "d2/db2/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Six.html", "d2/db2/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Six" ],
            [ "List_of_Gamma_control_faces_Double", "d5/d6d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Double.html", "d5/d6d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Double" ],
            [ "List_of_Gamma_control_faces_One_Two", "d9/dc8/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One__Two.html", "d9/dc8/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One__Two" ],
            [ "List_of_Gamma_control_faces_One_Three", "dd/d27/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One__Three.html", "dd/d27/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One__Three" ],
            [ "List_of_Gamma_control_faces_One_Four", "de/d6a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One__Four.html", "de/d6a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__One__Four" ],
            [ "List_of_Gamma_control_faces_Two_One", "d9/d9b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two__One.html", "d9/d9b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two__One" ],
            [ "List_of_Gamma_control_faces_Two_Three", "d5/d26/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two__Three.html", "d5/d26/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two__Three" ],
            [ "List_of_Gamma_control_faces_Two_Four", "df/dfc/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two__Four.html", "df/dfc/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Two__Four" ],
            [ "List_of_Gamma_control_faces_Three_One", "dd/db7/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three__One.html", "dd/db7/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three__One" ],
            [ "List_of_Gamma_control_faces_Three_Two", "dd/d53/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three__Two.html", "dd/d53/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three__Two" ],
            [ "List_of_Gamma_control_faces_Three_Four", "d7/d9d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three__Four.html", "d7/d9d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Three__Four" ],
            [ "List_of_Gamma_control_faces_Four_One", "de/d5e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four__One.html", "de/d5e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four__One" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d4/d64/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four__Two.html", "d4/d64/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four__Two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "dc/da3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four__Three.html", "dc/da3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1List__of__Gamma__control__faces__Four__Three" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "d6/da3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1Multiple__controls__and__homogeneous__boundary__conditions.html", null ]
          ] ],
          [ "square", "d9/d67/namespacefemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square.html", [
            [ "List_of_Gamma_control_faces_Single", "dd/de5/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Single.html", "dd/de5/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Single" ],
            [ "List_of_Gamma_control_faces_One", "d0/d35/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One.html", "d0/d35/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One" ],
            [ "List_of_Gamma_control_faces_Two", "da/d42/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two.html", "da/d42/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two" ],
            [ "List_of_Gamma_control_faces_Three", "d5/daf/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three.html", "d5/daf/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three" ],
            [ "List_of_Gamma_control_faces_Four", "d4/da1/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four.html", "d4/da1/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four" ],
            [ "List_of_Gamma_control_faces_Double", "df/db7/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Double.html", "df/db7/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Double" ],
            [ "List_of_Gamma_control_faces_One_Two", "d5/d26/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Two.html", "d5/d26/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Two" ],
            [ "List_of_Gamma_control_faces_One_Three", "d6/da9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three.html", "d6/da9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three" ],
            [ "List_of_Gamma_control_faces_One_Four", "dd/db3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Four.html", "dd/db3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Four" ],
            [ "List_of_Gamma_control_faces_Two_One", "d6/de4/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__One.html", "d6/de4/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__One" ],
            [ "List_of_Gamma_control_faces_Two_Three", "dc/dae/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Three.html", "dc/dae/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Three" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d7/de3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Four.html", "d7/de3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Four" ],
            [ "List_of_Gamma_control_faces_Three_One", "d8/d75/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__One.html", "d8/d75/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__One" ],
            [ "List_of_Gamma_control_faces_Three_Two", "d1/d6d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Two.html", "d1/d6d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Two" ],
            [ "List_of_Gamma_control_faces_Three_Four", "d3/d9e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Four.html", "d3/d9e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Four" ],
            [ "List_of_Gamma_control_faces_Four_One", "d2/daf/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__One.html", "d2/daf/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__One" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d4/def/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__Two.html", "d4/def/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__Two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "d8/d35/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__Three.html", "d8/d35/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__Three" ],
            [ "List_of_Gamma_control_faces_Triple", "d3/dfc/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Triple.html", "d3/dfc/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Triple" ],
            [ "List_of_Gamma_control_faces_One_Three_Two", "d2/d83/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two.html", "d2/d83/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two" ],
            [ "List_of_Gamma_control_faces_One_Four_Two", "d6/d32/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Four__Two.html", "d6/d32/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Four__Two" ],
            [ "List_of_Gamma_control_faces_One_Three_Four", "d3/d19/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three__Four.html", "d3/d19/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three__Four" ],
            [ "List_of_Gamma_control_faces_One_Four_Three", "db/db2/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Four__Three.html", "db/db2/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Four__Three" ],
            [ "List_of_Gamma_control_faces_Two_Three_One", "d8/d63/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Three__One.html", "d8/d63/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Three__One" ],
            [ "List_of_Gamma_control_faces_Two_Four_One", "db/d28/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Four__One.html", "db/d28/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Four__One" ],
            [ "List_of_Gamma_control_faces_Two_Three_Four", "da/d9f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Three__Four.html", "da/d9f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Three__Four" ],
            [ "List_of_Gamma_control_faces_Two_Four_Three", "df/d54/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Four__Three.html", "df/d54/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Two__Four__Three" ],
            [ "List_of_Gamma_control_faces_Three_One_Four", "d4/da3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__One__Four.html", "d4/da3/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__One__Four" ],
            [ "List_of_Gamma_control_faces_Three_Two_Four", "dd/d81/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Two__Four.html", "dd/d81/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Two__Four" ],
            [ "List_of_Gamma_control_faces_Three_One_Two", "d3/d16/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__One__Two.html", "d3/d16/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__One__Two" ],
            [ "List_of_Gamma_control_faces_Three_Two_One", "d7/d6c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Two__One.html", "d7/d6c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Three__Two__One" ],
            [ "List_of_Gamma_control_faces_Four_One_Three", "d5/d41/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__One__Three.html", "d5/d41/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__One__Three" ],
            [ "List_of_Gamma_control_faces_Four_Two_Three", "d2/dc9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__Two__Three.html", "d2/dc9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__Two__Three" ],
            [ "List_of_Gamma_control_faces_Four_One_Two", "da/d94/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__One__Two.html", "da/d94/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Four__One__Two" ],
            [ "List_of_Gamma_control_faces_Quadruple", "dc/d3d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Quadruple.html", "dc/d3d/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__Quadruple" ],
            [ "List_of_Gamma_control_faces_One_Three_Two_Four", "dd/d4c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two__Four.html", "dd/d4c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two__Four" ],
            [ "Boundary_Condition_control_between_extreme", "df/d6c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Boundary__Condition__control__between__extreme.html", "df/d6c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Boundary__Condition__control__between__extreme" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "dc/d22/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Multiple__controls__and__3261f6624b9d32e3f4562cce73a82b8c.html", "dc/d22/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Multiple__controls__and__3261f6624b9d32e3f4562cce73a82b8c" ],
            [ "Multiple_controls_in_front_constant", "d1/d37/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Multiple__controls__in__front__constant.html", "d1/d37/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Multiple__controls__in__front__constant" ],
            [ "Single_control_in_front_linear", "d0/d29/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Single__control__in__front__linear.html", "d0/d29/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Single__control__in__front__linear" ],
            [ "Double_controls_adjacent_in_front_linear", "d8/d3e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Double__controls__adjacent__in__front__linear.html", "d8/d3e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Double__controls__adjacent__in__front__linear" ],
            [ "Triple_controls_adjacent_in_front_linear", "d9/d04/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Triple__controls__adjacent__in__front__linear.html", "d9/d04/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1Triple__controls__adjacent__in__front__linear" ]
          ] ]
        ] ],
        [ "boundary_control_full_face", "d4/d1c/namespacefemus_1_1ctrl_1_1boundary__control__full__face.html", [
          [ "cube", "db/d4a/namespacefemus_1_1ctrl_1_1boundary__control__full__face_1_1cube.html", [
            [ "List_of_Gamma_control_faces_Single", "d0/d3f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Single.html", "d0/d3f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Single" ],
            [ "List_of_Gamma_control_faces_One", "de/d43/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One.html", "de/d43/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One" ],
            [ "List_of_Gamma_control_faces_Two", "d0/d5d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two.html", "d0/d5d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two" ],
            [ "List_of_Gamma_control_faces_Three", "d7/dd7/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three.html", "d7/dd7/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three" ],
            [ "List_of_Gamma_control_faces_Four", "d1/dc8/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four.html", "d1/dc8/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four" ],
            [ "List_of_Gamma_control_faces_Five", "db/de9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Five.html", "db/de9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Five" ],
            [ "List_of_Gamma_control_faces_Six", "d0/d4b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Six.html", "d0/d4b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Six" ],
            [ "List_of_Gamma_control_faces_Double", "d0/dff/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Double.html", "d0/dff/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Double" ],
            [ "List_of_Gamma_control_faces_One_Two", "de/d9f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One__Two.html", "de/d9f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One__Two" ],
            [ "List_of_Gamma_control_faces_One_Three", "d2/db6/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One__Three.html", "d2/db6/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One__Three" ],
            [ "List_of_Gamma_control_faces_One_Four", "d6/d5c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One__Four.html", "d6/d5c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__One__Four" ],
            [ "List_of_Gamma_control_faces_Two_One", "d7/d0f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two__One.html", "d7/d0f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two__One" ],
            [ "List_of_Gamma_control_faces_Two_Three", "de/dca/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two__Three.html", "de/dca/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two__Three" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d1/da9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two__Four.html", "d1/da9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Two__Four" ],
            [ "List_of_Gamma_control_faces_Three_One", "d7/dd2/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three__One.html", "d7/dd2/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three__One" ],
            [ "List_of_Gamma_control_faces_Three_Two", "d5/dc1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three__Two.html", "d5/dc1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three__Two" ],
            [ "List_of_Gamma_control_faces_Three_Four", "df/d37/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three__Four.html", "df/d37/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Three__Four" ],
            [ "List_of_Gamma_control_faces_Four_One", "de/dcb/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four__One.html", "de/dcb/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four__One" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d8/dcd/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four__Two.html", "d8/dcd/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four__Two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "d4/d3b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four__Three.html", "d4/d3b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1List__of__Gamma__control__faces__Four__Three" ]
          ] ],
          [ "square", "d1/df1/namespacefemus_1_1ctrl_1_1boundary__control__full__face_1_1square.html", [
            [ "List_of_Gamma_control_faces_Single", "d7/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Single.html", "d7/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Single" ],
            [ "List_of_Gamma_control_faces_One", "de/dbf/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One.html", "de/dbf/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One" ],
            [ "List_of_Gamma_control_faces_Two", "d1/ddf/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two.html", "d1/ddf/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two" ],
            [ "List_of_Gamma_control_faces_Three", "db/d92/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three.html", "db/d92/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three" ],
            [ "List_of_Gamma_control_faces_Four", "da/d94/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four.html", "da/d94/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four" ],
            [ "List_of_Gamma_control_faces_Double", "d4/d14/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Double.html", "d4/d14/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Double" ],
            [ "List_of_Gamma_control_faces_One_Two", "d0/d20/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Two.html", "d0/d20/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Two" ],
            [ "List_of_Gamma_control_faces_One_Three", "da/df2/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three.html", "da/df2/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three" ],
            [ "List_of_Gamma_control_faces_One_Four", "df/d07/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Four.html", "df/d07/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Four" ],
            [ "List_of_Gamma_control_faces_Two_One", "d9/d2f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__One.html", "d9/d2f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__One" ],
            [ "List_of_Gamma_control_faces_Two_Three", "d9/d3f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Three.html", "d9/d3f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Three" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d6/d96/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Four.html", "d6/d96/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Four" ],
            [ "List_of_Gamma_control_faces_Three_One", "da/df8/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__One.html", "da/df8/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__One" ],
            [ "List_of_Gamma_control_faces_Three_Two", "d7/ddd/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Two.html", "d7/ddd/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Two" ],
            [ "List_of_Gamma_control_faces_Three_Four", "df/d15/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Four.html", "df/d15/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Four" ],
            [ "List_of_Gamma_control_faces_Four_One", "d0/dd5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__One.html", "d0/dd5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__One" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d5/dd1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__Two.html", "d5/dd1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__Two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "d4/db9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__Three.html", "d4/db9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__Three" ],
            [ "List_of_Gamma_control_faces_Triple", "d3/d4e/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Triple.html", "d3/d4e/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Triple" ],
            [ "List_of_Gamma_control_faces_One_Three_Two", "d7/d65/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two.html", "d7/d65/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two" ],
            [ "List_of_Gamma_control_faces_One_Four_Two", "de/d8b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Four__Two.html", "de/d8b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Four__Two" ],
            [ "List_of_Gamma_control_faces_One_Three_Four", "d0/dc1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three__Four.html", "d0/dc1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three__Four" ],
            [ "List_of_Gamma_control_faces_One_Four_Three", "d8/dbe/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Four__Three.html", "d8/dbe/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Four__Three" ],
            [ "List_of_Gamma_control_faces_Two_Three_One", "d9/de1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Three__One.html", "d9/de1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Three__One" ],
            [ "List_of_Gamma_control_faces_Two_Four_One", "db/ddf/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Four__One.html", "db/ddf/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Four__One" ],
            [ "List_of_Gamma_control_faces_Two_Three_Four", "dd/d8d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Three__Four.html", "dd/d8d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Three__Four" ],
            [ "List_of_Gamma_control_faces_Two_Four_Three", "d3/d85/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Four__Three.html", "d3/d85/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Two__Four__Three" ],
            [ "List_of_Gamma_control_faces_Three_One_Four", "d7/d19/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__One__Four.html", "d7/d19/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__One__Four" ],
            [ "List_of_Gamma_control_faces_Three_Two_Four", "db/d57/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Two__Four.html", "db/d57/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Two__Four" ],
            [ "List_of_Gamma_control_faces_Three_One_Two", "d7/dfd/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__One__Two.html", "d7/dfd/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__One__Two" ],
            [ "List_of_Gamma_control_faces_Three_Two_One", "d7/d1d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Two__One.html", "d7/d1d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Three__Two__One" ],
            [ "List_of_Gamma_control_faces_Four_One_Three", "d3/d8c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__One__Three.html", "d3/d8c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__One__Three" ],
            [ "List_of_Gamma_control_faces_Four_Two_Three", "d0/dba/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__Two__Three.html", "d0/dba/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__Two__Three" ],
            [ "List_of_Gamma_control_faces_Four_One_Two", "d6/d23/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__One__Two.html", "d6/d23/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Four__One__Two" ],
            [ "List_of_Gamma_control_faces_Quadruple", "d3/df7/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Quadruple.html", "d3/df7/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__Quadruple" ],
            [ "List_of_Gamma_control_faces_One_Three_Two_Four", "dd/db4/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two__Four.html", "dd/db4/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1List__of__Gamma__control__faces__One__Three__Two__Four" ],
            [ "Boundary_Condition_control_full_face", "d2/d06/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Boundary__Condition__control__full__face.html", "d2/d06/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Boundary__Condition__control__full__face" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "de/d0a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Multiple__controls__and__homogeneous__boundary__conditions.html", "de/d0a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Multiple__controls__and__homogeneous__boundary__conditions" ],
            [ "Multiple_controls_in_front_constant", "db/df9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Multiple__controls__in__front__constant.html", "db/df9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Multiple__controls__in__front__constant" ],
            [ "Single_control_in_front_linear", "df/d46/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Single__control__in__front__linear.html", "df/d46/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Single__control__in__front__linear" ],
            [ "Double_controls_adjacent_in_front_linear", "d8/d8a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Double__controls__adjacent__in__front__linear.html", "d8/d8a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Double__controls__adjacent__in__front__linear" ],
            [ "Triple_controls_adjacent_in_front_linear", "d7/d92/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Triple__controls__adjacent__in__front__linear.html", "d7/d92/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1Triple__controls__adjacent__in__front__linear" ]
          ] ]
        ] ],
        [ "cube", "df/dfc/namespacefemus_1_1ctrl_1_1cube.html", [
          [ "cost_functional_without_regularization", "dd/d03/classfemus_1_1ctrl_1_1cube_1_1cost__functional__without__regularization.html", null ]
        ] ],
        [ "square", "d1/d71/namespacefemus_1_1ctrl_1_1square.html", [
          [ "cost_functional_without_regularization", "d1/dc7/classfemus_1_1ctrl_1_1square_1_1cost__functional__without__regularization.html", null ]
        ] ],
        [ "square_or_cube", "db/dec/namespacefemus_1_1ctrl_1_1square__or__cube.html", [
          [ "List_of_faces", "de/d73/classfemus_1_1ctrl_1_1square__or__cube_1_1List__of__faces.html", "de/d73/classfemus_1_1ctrl_1_1square__or__cube_1_1List__of__faces" ],
          [ "List_of_Gamma_control_faces", "d5/d08/classfemus_1_1ctrl_1_1square__or__cube_1_1List__of__Gamma__control__faces.html", "d5/d08/classfemus_1_1ctrl_1_1square__or__cube_1_1List__of__Gamma__control__faces" ],
          [ "Domain_elements_containing_Gamma_control", "d5/da5/classfemus_1_1ctrl_1_1square__or__cube_1_1Domain__elements__containing__Gamma__control.html", null ],
          [ "pure_boundary", "de/db9/classfemus_1_1ctrl_1_1square__or__cube_1_1pure__boundary.html", "de/db9/classfemus_1_1ctrl_1_1square__or__cube_1_1pure__boundary" ],
          [ "lifting_internal", "d7/d7b/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__internal.html", "d7/d7b/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__internal" ],
          [ "lifting_external", "d2/da1/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__external.html", "d2/da1/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__external" ],
          [ "Boundary_Condition", "dd/d0e/classfemus_1_1ctrl_1_1square__or__cube_1_1Boundary__Condition.html", "dd/d0e/classfemus_1_1ctrl_1_1square__or__cube_1_1Boundary__Condition" ],
          [ "cost_functional_without_regularization", "dd/d48/classfemus_1_1ctrl_1_1square__or__cube_1_1cost__functional__without__regularization.html", "dd/d48/classfemus_1_1ctrl_1_1square__or__cube_1_1cost__functional__without__regularization" ],
          [ "mixed_state_or_ctrl_inequality", "d9/ddd/classfemus_1_1ctrl_1_1square__or__cube_1_1mixed__state__or__ctrl__inequality.html", "d9/ddd/classfemus_1_1ctrl_1_1square__or__cube_1_1mixed__state__or__ctrl__inequality" ]
        ] ],
        [ "cost_functional", "d0/dec/classfemus_1_1ctrl_1_1cost__functional.html", "d0/dec/classfemus_1_1ctrl_1_1cost__functional" ],
        [ "cost_functional_without_regularization", "d0/dc3/classfemus_1_1ctrl_1_1cost__functional__without__regularization.html", null ],
        [ "mixed_state_or_ctrl_inequality", "d2/dd1/classfemus_1_1ctrl_1_1mixed__state__or__ctrl__inequality.html", "d2/dd1/classfemus_1_1ctrl_1_1mixed__state__or__ctrl__inequality" ],
        [ "Gamma_control_equation_fractional_sobolev_differentiability_index", "d2/dff/classfemus_1_1ctrl_1_1Gamma__control__equation__fractional__sobolev__differentiability__index.html", "d2/dff/classfemus_1_1ctrl_1_1Gamma__control__equation__fractional__sobolev__differentiability__index" ],
        [ "Gamma_control_equation_integer_sobolev_differentiability_index", "dd/db0/classfemus_1_1ctrl_1_1Gamma__control__equation__integer__sobolev__differentiability__index.html", "dd/db0/classfemus_1_1ctrl_1_1Gamma__control__equation__integer__sobolev__differentiability__index" ],
        [ "Domain_of_PDE", "d7/d47/classfemus_1_1ctrl_1_1Domain__of__PDE.html", "d7/d47/classfemus_1_1ctrl_1_1Domain__of__PDE" ]
      ] ],
      [ "elliptic", "df/d9f/namespacefemus_1_1elliptic.html", [
        [ "pure_boundary", "dd/d57/classfemus_1_1elliptic_1_1pure__boundary.html", "dd/d57/classfemus_1_1elliptic_1_1pure__boundary" ],
        [ "lifting_internal", "d8/dea/classfemus_1_1elliptic_1_1lifting__internal.html", "d8/dea/classfemus_1_1elliptic_1_1lifting__internal" ],
        [ "lifting_external", "d7/d9a/classfemus_1_1elliptic_1_1lifting__external.html", "d7/d9a/classfemus_1_1elliptic_1_1lifting__external" ]
      ] ],
      [ "Math", "d3/d25/namespacefemus_1_1Math.html", [
        [ "Function", "db/dc9/classfemus_1_1Math_1_1Function.html", "db/dc9/classfemus_1_1Math_1_1Function" ]
      ] ],
      [ "navier_stokes", "d3/de9/namespacefemus_1_1navier__stokes.html", [
        [ "pure_boundary", "d1/d8e/classfemus_1_1navier__stokes_1_1pure__boundary.html", "d1/d8e/classfemus_1_1navier__stokes_1_1pure__boundary" ],
        [ "lifting_internal", "d2/dc8/classfemus_1_1navier__stokes_1_1lifting__internal.html", "d2/dc8/classfemus_1_1navier__stokes_1_1lifting__internal" ]
      ] ],
      [ "Parallel", "db/db2/namespacefemus_1_1Parallel.html", [
        [ "data_type", "db/db2/namespacefemus_1_1Parallel.html#d7/da0/structfemus_1_1Parallel_1_1data__type", null ],
        [ "request", "db/db2/namespacefemus_1_1Parallel.html#d1/d44/structfemus_1_1Parallel_1_1request", null ],
        [ "status", "db/db2/namespacefemus_1_1Parallel.html#d5/dde/structfemus_1_1Parallel_1_1status", null ],
        [ "DataType", "d3/d0e/classfemus_1_1Parallel_1_1DataType.html", "d3/d0e/classfemus_1_1Parallel_1_1DataType" ],
        [ "Status", "d5/d01/classfemus_1_1Parallel_1_1Status.html", "d5/d01/classfemus_1_1Parallel_1_1Status" ],
        [ "Request", "df/d8f/classfemus_1_1Parallel_1_1Request.html", "df/d8f/classfemus_1_1Parallel_1_1Request" ]
      ] ],
      [ "FemusInit", "d6/d8c/classfemus_1_1FemusInit.html", "d6/d8c/classfemus_1_1FemusInit" ],
      [ "Files", "d4/d91/classfemus_1_1Files.html", "d4/d91/classfemus_1_1Files" ],
      [ "FemusInputParser", "d7/d4b/classfemus_1_1FemusInputParser.html", "d7/d4b/classfemus_1_1FemusInputParser" ],
      [ "HtmlInputParser", "de/d29/classfemus_1_1HtmlInputParser.html", "de/d29/classfemus_1_1HtmlInputParser" ],
      [ "InputParser", "df/dcd/classfemus_1_1InputParser.html", "df/dcd/classfemus_1_1InputParser" ],
      [ "JsonInputParser", "d0/d0b/classfemus_1_1JsonInputParser.html", "d0/d0b/classfemus_1_1JsonInputParser" ],
      [ "MyMatrix", "de/d21/classfemus_1_1MyMatrix.html", "de/d21/classfemus_1_1MyMatrix" ],
      [ "MyVector", "dd/d04/classfemus_1_1MyVector.html", "dd/d04/classfemus_1_1MyVector" ],
      [ "ParallelObject", "d2/df1/classfemus_1_1ParallelObject.html", "d2/df1/classfemus_1_1ParallelObject" ],
      [ "MultiLevelProblem", "d8/d26/classfemus_1_1MultiLevelProblem.html", "d8/d26/classfemus_1_1MultiLevelProblem" ],
      [ "GeomElemBase", "da/db1/classfemus_1_1GeomElemBase.html", "da/db1/classfemus_1_1GeomElemBase" ],
      [ "GeomElemEdge2", "d4/dc4/classfemus_1_1GeomElemEdge2.html", "d4/dc4/classfemus_1_1GeomElemEdge2" ],
      [ "GeomElemEdge3", "d4/d9a/classfemus_1_1GeomElemEdge3.html", "d4/d9a/classfemus_1_1GeomElemEdge3" ],
      [ "GeomElemHex27", "d4/d75/classfemus_1_1GeomElemHex27.html", "d4/d75/classfemus_1_1GeomElemHex27" ],
      [ "GeomElemHex8", "df/d89/classfemus_1_1GeomElemHex8.html", "df/d89/classfemus_1_1GeomElemHex8" ],
      [ "GeomElemQuad4", "df/de5/classfemus_1_1GeomElemQuad4.html", "df/de5/classfemus_1_1GeomElemQuad4" ],
      [ "GeomElemQuad9", "d2/dba/classfemus_1_1GeomElemQuad9.html", "d2/dba/classfemus_1_1GeomElemQuad9" ],
      [ "GeomElemTet10", "d3/d98/classfemus_1_1GeomElemTet10.html", "d3/d98/classfemus_1_1GeomElemTet10" ],
      [ "GeomElemTet4", "d2/d6c/classfemus_1_1GeomElemTet4.html", "d2/d6c/classfemus_1_1GeomElemTet4" ],
      [ "GeomElemTri3", "d0/d1f/classfemus_1_1GeomElemTri3.html", "d0/d1f/classfemus_1_1GeomElemTri3" ],
      [ "GeomElemTri6", "dc/db4/classfemus_1_1GeomElemTri6.html", "dc/db4/classfemus_1_1GeomElemTri6" ],
      [ "GeomElemTri7", "d5/d7d/classfemus_1_1GeomElemTri7.html", "d5/d7d/classfemus_1_1GeomElemTri7" ],
      [ "GambitIO", "d3/d55/classfemus_1_1GambitIO.html", "d3/d55/classfemus_1_1GambitIO" ],
      [ "MeshInput", "d1/d91/classfemus_1_1MeshInput.html", "d1/d91/classfemus_1_1MeshInput" ],
      [ "MeshASMPartitioning", "d6/d5b/classfemus_1_1MeshASMPartitioning.html", "d6/d5b/classfemus_1_1MeshASMPartitioning" ],
      [ "MeshMetisPartitioning", "dc/d3d/classfemus_1_1MeshMetisPartitioning.html", "dc/d3d/classfemus_1_1MeshMetisPartitioning" ],
      [ "MeshPartitioning", "d1/d51/classfemus_1_1MeshPartitioning.html", "d1/d51/classfemus_1_1MeshPartitioning" ],
      [ "MeshRefinement", "d3/d59/classfemus_1_1MeshRefinement.html", "d3/d59/classfemus_1_1MeshRefinement" ],
      [ "elem", "db/d2e/classfemus_1_1elem.html", "db/d2e/classfemus_1_1elem" ],
      [ "Box", "d8/d66/classfemus_1_1Box.html", "d8/d66/classfemus_1_1Box" ],
      [ "Domain", "df/d1a/classfemus_1_1Domain.html", "df/d1a/classfemus_1_1Domain" ],
      [ "ElemStoBase", "d2/d68/classfemus_1_1ElemStoBase.html", "d2/d68/classfemus_1_1ElemStoBase" ],
      [ "ElemStoVol", "d8/d48/classfemus_1_1ElemStoVol.html", "d8/d48/classfemus_1_1ElemStoVol" ],
      [ "ElemStoBdry", "d9/d79/classfemus_1_1ElemStoBdry.html", "d9/d79/classfemus_1_1ElemStoBdry" ],
      [ "NodeSto", "d7/dd5/classfemus_1_1NodeSto.html", "d7/dd5/classfemus_1_1NodeSto" ],
      [ "GenCase", "de/d9f/classfemus_1_1GenCase.html", "de/d9f/classfemus_1_1GenCase" ],
      [ "MultiLevelMeshTwo", "d7/df0/classfemus_1_1MultiLevelMeshTwo.html", "d7/df0/classfemus_1_1MultiLevelMeshTwo" ],
      [ "Mesh", "d6/db7/classfemus_1_1Mesh.html", "d6/db7/classfemus_1_1Mesh" ],
      [ "MultiLevelMesh", "d7/d9c/classfemus_1_1MultiLevelMesh.html", "d7/d9c/classfemus_1_1MultiLevelMesh" ],
      [ "GMVWriter", "d4/d0f/classfemus_1_1GMVWriter.html", "d4/d0f/classfemus_1_1GMVWriter" ],
      [ "VTKWriter", "dd/d3b/classfemus_1_1VTKWriter.html", "dd/d3b/classfemus_1_1VTKWriter" ],
      [ "Writer", "d4/d83/classfemus_1_1Writer.html", "d4/d83/classfemus_1_1Writer" ],
      [ "Solution_generation_single_level", "d5/df1/classfemus_1_1Solution__generation__single__level.html", "d5/df1/classfemus_1_1Solution__generation__single__level" ],
      [ "FE_convergence", "dd/d36/classfemus_1_1FE__convergence.html", "dd/d36/classfemus_1_1FE__convergence" ],
      [ "MultiLevelSolution", "db/d17/classfemus_1_1MultiLevelSolution.html", "db/d17/classfemus_1_1MultiLevelSolution" ],
      [ "Solution", "d0/da2/classfemus_1_1Solution.html", "d0/da2/classfemus_1_1Solution" ],
      [ "poisson_equation", "d5/dbd/classfemus_1_1poisson__equation.html", "d5/dbd/classfemus_1_1poisson__equation" ],
      [ "app_specifics", "dd/d15/classfemus_1_1app__specifics.html", "dd/d15/classfemus_1_1app__specifics" ],
      [ "assemble_jacobian", "d4/d7a/classfemus_1_1assemble__jacobian.html", "d4/d7a/classfemus_1_1assemble__jacobian" ],
      [ "Phi", "df/d45/classfemus_1_1Phi.html", "df/d45/classfemus_1_1Phi" ],
      [ "Unknown", "d8/dea/namespacefemus.html#d7/d34/classfemus_1_1Unknown", "d8/dea/namespacefemus_d7/d34/classfemus_1_1Unknown_dup" ],
      [ "UnknownLocal", "d0/d27/classfemus_1_1UnknownLocal.html", "d0/d27/classfemus_1_1UnknownLocal" ],
      [ "ElementJacRes", "d2/dae/classfemus_1_1ElementJacRes.html", "d2/dae/classfemus_1_1ElementJacRes" ],
      [ "BoundaryConditions", "d8/de0/classfemus_1_1BoundaryConditions.html", "d8/de0/classfemus_1_1BoundaryConditions" ],
      [ "CurrentElem", "d8/d49/classfemus_1_1CurrentElem.html", "d8/d49/classfemus_1_1CurrentElem" ],
      [ "CurrentQuantity", "d9/d4a/classfemus_1_1CurrentQuantity.html", "d9/d4a/classfemus_1_1CurrentQuantity" ],
      [ "DofMap", "db/d02/classfemus_1_1DofMap.html", "db/d02/classfemus_1_1DofMap" ],
      [ "Quantity", "d8/d0e/classfemus_1_1Quantity.html", "d8/d0e/classfemus_1_1Quantity" ],
      [ "QuantityMap", "de/d15/classfemus_1_1QuantityMap.html", "de/d15/classfemus_1_1QuantityMap" ],
      [ "SystemTwo", "db/d19/classfemus_1_1SystemTwo.html", "db/d19/classfemus_1_1SystemTwo" ],
      [ "TimeLoop", "d7/dc0/classfemus_1_1TimeLoop.html", "d7/dc0/classfemus_1_1TimeLoop" ],
      [ "ExplicitSystem", "d5/d2d/classfemus_1_1ExplicitSystem.html", "d5/d2d/classfemus_1_1ExplicitSystem" ],
      [ "ImplicitSystem", "d2/d6a/classfemus_1_1ImplicitSystem.html", "d2/d6a/classfemus_1_1ImplicitSystem" ],
      [ "LinearImplicitSystem", "d7/d82/classfemus_1_1LinearImplicitSystem.html", "d7/d82/classfemus_1_1LinearImplicitSystem" ],
      [ "MonolithicFSINonLinearImplicitSystem", "d3/d48/classfemus_1_1MonolithicFSINonLinearImplicitSystem.html", "d3/d48/classfemus_1_1MonolithicFSINonLinearImplicitSystem" ],
      [ "NonLinearImplicitSystem", "d5/d10/classfemus_1_1NonLinearImplicitSystem.html", "d5/d10/classfemus_1_1NonLinearImplicitSystem" ],
      [ "System", "d4/d23/classfemus_1_1System.html", "d4/d23/classfemus_1_1System" ],
      [ "ImplicitRungeKuttaSystem", "d3/d06/classfemus_1_1ImplicitRungeKuttaSystem.html", "d3/d06/classfemus_1_1ImplicitRungeKuttaSystem" ],
      [ "NewmarkTransientSystem", "dd/dcc/classfemus_1_1NewmarkTransientSystem.html", "dd/dcc/classfemus_1_1NewmarkTransientSystem" ],
      [ "TransientSystem", "d9/d11/classfemus_1_1TransientSystem.html", "d9/d11/classfemus_1_1TransientSystem" ],
      [ "DenseMatrix", "d2/d19/classfemus_1_1DenseMatrix.html", "d2/d19/classfemus_1_1DenseMatrix" ],
      [ "DenseMatrixBase", "dc/d0f/classfemus_1_1DenseMatrixBase.html", "dc/d0f/classfemus_1_1DenseMatrixBase" ],
      [ "DenseSubMatrix", "df/dc9/classfemus_1_1DenseSubMatrix.html", "df/dc9/classfemus_1_1DenseSubMatrix" ],
      [ "DenseSubVector", "dc/dd4/classfemus_1_1DenseSubVector.html", "dc/dd4/classfemus_1_1DenseSubVector" ],
      [ "DenseVector", "da/d5a/classfemus_1_1DenseVector.html", "da/d5a/classfemus_1_1DenseVector" ],
      [ "DenseVectorBase", "d4/d34/classfemus_1_1DenseVectorBase.html", "d4/d34/classfemus_1_1DenseVectorBase" ],
      [ "FieldSplitTree", "d0/daf/classfemus_1_1FieldSplitTree.html", "d0/daf/classfemus_1_1FieldSplitTree" ],
      [ "FunctionBase", "d2/da8/classfemus_1_1FunctionBase.html", "d2/da8/classfemus_1_1FunctionBase" ],
      [ "Graph", "d4/d36/classfemus_1_1Graph.html", "d4/d36/classfemus_1_1Graph" ],
      [ "LinearEquation", "d8/d3d/classfemus_1_1LinearEquation.html", "d8/d3d/classfemus_1_1LinearEquation" ],
      [ "LinearEquationSolver", "d7/d8c/classfemus_1_1LinearEquationSolver.html", "d7/d8c/classfemus_1_1LinearEquationSolver" ],
      [ "LinearEquationSolverPetsc", "d7/dad/classfemus_1_1LinearEquationSolverPetsc.html", "d7/dad/classfemus_1_1LinearEquationSolverPetsc" ],
      [ "LinearEquationSolverPetscAsm", "dc/daf/classfemus_1_1LinearEquationSolverPetscAsm.html", "dc/daf/classfemus_1_1LinearEquationSolverPetscAsm" ],
      [ "LinearEquationSolverPetscFieldSplit", "d5/d86/classfemus_1_1LinearEquationSolverPetscFieldSplit.html", "d5/d86/classfemus_1_1LinearEquationSolverPetscFieldSplit" ],
      [ "NumericVector", "db/dcb/classfemus_1_1NumericVector.html", "db/dcb/classfemus_1_1NumericVector" ],
      [ "ParsedFunction", "d6/d62/classfemus_1_1ParsedFunction.html", "d6/d62/classfemus_1_1ParsedFunction" ],
      [ "PetscMatrix", "d0/dbc/classfemus_1_1PetscMatrix.html", "d0/dbc/classfemus_1_1PetscMatrix" ],
      [ "PetscPreconditioner", "d6/db9/classfemus_1_1PetscPreconditioner.html", "d6/db9/classfemus_1_1PetscPreconditioner" ],
      [ "PetscVector", "de/dbb/classfemus_1_1PetscVector.html", "de/dbb/classfemus_1_1PetscVector" ],
      [ "Preconditioner", "d7/df0/classfemus_1_1Preconditioner.html", "d7/df0/classfemus_1_1Preconditioner" ],
      [ "SparseMatrix", "d4/d37/classfemus_1_1SparseMatrix.html", "d4/d37/classfemus_1_1SparseMatrix" ],
      [ "basis", "dc/d77/classfemus_1_1basis.html", "dc/d77/classfemus_1_1basis" ],
      [ "hex_lag", "d9/d7c/classfemus_1_1hex__lag.html", "d9/d7c/classfemus_1_1hex__lag" ],
      [ "HexLinear", "dc/d08/classfemus_1_1HexLinear.html", "dc/d08/classfemus_1_1HexLinear" ],
      [ "HexQuadratic", "d7/daa/classfemus_1_1HexQuadratic.html", "d7/daa/classfemus_1_1HexQuadratic" ],
      [ "HexBiquadratic", "db/d28/classfemus_1_1HexBiquadratic.html", "db/d28/classfemus_1_1HexBiquadratic" ],
      [ "hex_const", "d2/d21/classfemus_1_1hex__const.html", "d2/d21/classfemus_1_1hex__const" ],
      [ "hex0", "db/dd3/classfemus_1_1hex0.html", "db/dd3/classfemus_1_1hex0" ],
      [ "hexpwLinear", "d5/de9/classfemus_1_1hexpwLinear.html", "d5/de9/classfemus_1_1hexpwLinear" ],
      [ "wedge_lag", "d3/db2/classfemus_1_1wedge__lag.html", "d3/db2/classfemus_1_1wedge__lag" ],
      [ "WedgeLinear", "d5/dc7/classfemus_1_1WedgeLinear.html", "d5/dc7/classfemus_1_1WedgeLinear" ],
      [ "WedgeQuadratic", "d4/d5d/classfemus_1_1WedgeQuadratic.html", "d4/d5d/classfemus_1_1WedgeQuadratic" ],
      [ "WedgeBiquadratic", "d8/d84/classfemus_1_1WedgeBiquadratic.html", "d8/d84/classfemus_1_1WedgeBiquadratic" ],
      [ "wedge_const", "df/d36/classfemus_1_1wedge__const.html", "df/d36/classfemus_1_1wedge__const" ],
      [ "wedge0", "d4/dfd/classfemus_1_1wedge0.html", "d4/dfd/classfemus_1_1wedge0" ],
      [ "wedgepwLinear", "d9/dca/classfemus_1_1wedgepwLinear.html", "d9/dca/classfemus_1_1wedgepwLinear" ],
      [ "tet_lag", "da/de4/classfemus_1_1tet__lag.html", "da/de4/classfemus_1_1tet__lag" ],
      [ "TetLinear", "d5/d31/classfemus_1_1TetLinear.html", "d5/d31/classfemus_1_1TetLinear" ],
      [ "TetQuadratic", "d7/d8e/classfemus_1_1TetQuadratic.html", "d7/d8e/classfemus_1_1TetQuadratic" ],
      [ "TetBiquadratic", "dc/d20/classfemus_1_1TetBiquadratic.html", "dc/d20/classfemus_1_1TetBiquadratic" ],
      [ "tet_const", "d2/d3b/classfemus_1_1tet__const.html", "d2/d3b/classfemus_1_1tet__const" ],
      [ "tet0", "da/d8f/classfemus_1_1tet0.html", "da/d8f/classfemus_1_1tet0" ],
      [ "tetpwLinear", "d8/dea/classfemus_1_1tetpwLinear.html", "d8/dea/classfemus_1_1tetpwLinear" ],
      [ "quad_lag", "d3/db3/classfemus_1_1quad__lag.html", "d3/db3/classfemus_1_1quad__lag" ],
      [ "QuadLinear", "d5/d51/classfemus_1_1QuadLinear.html", "d5/d51/classfemus_1_1QuadLinear" ],
      [ "QuadQuadratic", "db/ddf/classfemus_1_1QuadQuadratic.html", "db/ddf/classfemus_1_1QuadQuadratic" ],
      [ "QuadBiquadratic", "d5/d3b/classfemus_1_1QuadBiquadratic.html", "d5/d3b/classfemus_1_1QuadBiquadratic" ],
      [ "quad_const", "d9/d6e/classfemus_1_1quad__const.html", "d9/d6e/classfemus_1_1quad__const" ],
      [ "quad0", "d5/dca/classfemus_1_1quad0.html", "d5/dca/classfemus_1_1quad0" ],
      [ "quadpwLinear", "db/d38/classfemus_1_1quadpwLinear.html", "db/d38/classfemus_1_1quadpwLinear" ],
      [ "tri_lag", "d2/d57/classfemus_1_1tri__lag.html", "d2/d57/classfemus_1_1tri__lag" ],
      [ "TriLinear", "de/d1d/classfemus_1_1TriLinear.html", "de/d1d/classfemus_1_1TriLinear" ],
      [ "TriQuadratic", "dc/d6c/classfemus_1_1TriQuadratic.html", "dc/d6c/classfemus_1_1TriQuadratic" ],
      [ "TriBiquadratic", "d3/d45/classfemus_1_1TriBiquadratic.html", "d3/d45/classfemus_1_1TriBiquadratic" ],
      [ "tri_const", "d1/dc4/classfemus_1_1tri__const.html", "d1/dc4/classfemus_1_1tri__const" ],
      [ "tri0", "d1/d8f/classfemus_1_1tri0.html", "d1/d8f/classfemus_1_1tri0" ],
      [ "tripwLinear", "d2/ddf/classfemus_1_1tripwLinear.html", "d2/ddf/classfemus_1_1tripwLinear" ],
      [ "line_lag", "dd/da8/classfemus_1_1line__lag.html", "dd/da8/classfemus_1_1line__lag" ],
      [ "LineLinear", "d2/dce/classfemus_1_1LineLinear.html", "d2/dce/classfemus_1_1LineLinear" ],
      [ "LineBiquadratic", "dd/d15/classfemus_1_1LineBiquadratic.html", "dd/d15/classfemus_1_1LineBiquadratic" ],
      [ "line_const", "da/d3d/classfemus_1_1line__const.html", "da/d3d/classfemus_1_1line__const" ],
      [ "line0", "d7/d9a/classfemus_1_1line0.html", "d7/d9a/classfemus_1_1line0" ],
      [ "linepwLinear", "dd/dfa/classfemus_1_1linepwLinear.html", "dd/dfa/classfemus_1_1linepwLinear" ],
      [ "elem_type", "d3/dca/classfemus_1_1elem__type.html", "d3/dca/classfemus_1_1elem__type" ],
      [ "elem_type_1D", "d3/de0/classfemus_1_1elem__type__1D.html", "d3/de0/classfemus_1_1elem__type__1D" ],
      [ "elem_type_2D", "dd/d1d/classfemus_1_1elem__type__2D.html", "dd/d1d/classfemus_1_1elem__type__2D" ],
      [ "elem_type_3D", "d9/d98/classfemus_1_1elem__type__3D.html", "d9/d98/classfemus_1_1elem__type__3D" ],
      [ "elem_type_templ", "d6/dcf/classfemus_1_1elem__type__templ.html", "d6/dcf/classfemus_1_1elem__type__templ" ],
      [ "elem_type_templ< type, type_mov, 1, 3 >", "d8/d15/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_011_00_013_01_4.html", "d8/d15/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_011_00_013_01_4" ],
      [ "elem_type_templ< type, type_mov, 2, 3 >", "d1/dda/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_012_00_013_01_4.html", "d1/dda/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_012_00_013_01_4" ],
      [ "elem_type_templ< type, type_mov, 3, 3 >", "d9/df4/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_013_00_013_01_4.html", "d9/df4/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_013_00_013_01_4" ],
      [ "elem_type_templ_base", "da/ddf/classfemus_1_1elem__type__templ__base.html", "da/ddf/classfemus_1_1elem__type__templ__base" ],
      [ "hex_gauss", "d8/d5a/classfemus_1_1hex__gauss.html", "d8/d5a/classfemus_1_1hex__gauss" ],
      [ "wedge_gauss", "d9/d65/classfemus_1_1wedge__gauss.html", "d9/d65/classfemus_1_1wedge__gauss" ],
      [ "tet_gauss", "d3/d95/classfemus_1_1tet__gauss.html", "d3/d95/classfemus_1_1tet__gauss" ],
      [ "quad_gauss", "d2/d99/classfemus_1_1quad__gauss.html", "d2/d99/classfemus_1_1quad__gauss" ],
      [ "tri_gauss", "d5/d6f/classfemus_1_1tri__gauss.html", "d5/d6f/classfemus_1_1tri__gauss" ],
      [ "line_gauss", "d9/d01/classfemus_1_1line__gauss.html", "d9/d01/classfemus_1_1line__gauss" ],
      [ "point_gauss", "de/d84/classfemus_1_1point__gauss.html", "de/d84/classfemus_1_1point__gauss" ],
      [ "Gauss", "da/da7/classfemus_1_1Gauss.html", "da/da7/classfemus_1_1Gauss" ],
      [ "Line", "d4/db3/classfemus_1_1Line.html", "d4/db3/classfemus_1_1Line" ],
      [ "Marker", "d4/d0a/classfemus_1_1Marker.html", "d4/d0a/classfemus_1_1Marker" ],
      [ "pure_boundary", "df/dfc/classfemus_1_1pure__boundary.html", "df/dfc/classfemus_1_1pure__boundary" ],
      [ "lifting_internal", "d7/d2f/classfemus_1_1lifting__internal.html", "d7/d2f/classfemus_1_1lifting__internal" ],
      [ "lifting_external", "de/da3/classfemus_1_1lifting__external.html", "de/da3/classfemus_1_1lifting__external" ],
      [ "NonLinearImplicitSystemWithPrimalDualActiveSetMethod", "d4/d32/classfemus_1_1NonLinearImplicitSystemWithPrimalDualActiveSetMethod.html", "d4/d32/classfemus_1_1NonLinearImplicitSystemWithPrimalDualActiveSetMethod" ],
      [ "Fluid", "d3/d6c/classfemus_1_1Fluid.html", "d3/d6c/classfemus_1_1Fluid" ],
      [ "Material", "d8/d3b/classfemus_1_1Material.html", "d8/d3b/classfemus_1_1Material" ],
      [ "Parameter", "d0/d0e/classfemus_1_1Parameter.html", "d0/d0e/classfemus_1_1Parameter" ],
      [ "Gravity", "df/df6/classfemus_1_1Gravity.html", "df/df6/classfemus_1_1Gravity" ],
      [ "Parameters", "d1/daa/classfemus_1_1Parameters.html", "d1/daa/classfemus_1_1Parameters" ],
      [ "Solid", "d3/d04/classfemus_1_1Solid.html", "d3/d04/classfemus_1_1Solid" ],
      [ "sparseGrid", "dc/d98/classfemus_1_1sparseGrid.html", "dc/d98/classfemus_1_1sparseGrid" ],
      [ "uq", "d6/dc3/classfemus_1_1uq.html", "d6/dc3/classfemus_1_1uq" ],
      [ "OptLoop", "da/d6b/classfemus_1_1OptLoop.html", "da/d6b/classfemus_1_1OptLoop" ]
    ] ],
    [ "array", "d2/d41/classarray.html", "d2/d41/classarray" ],
    [ "GMPM", "d0/d10/classGMPM.html", "d0/d10/classGMPM" ],
    [ "MagnFieldExtLagMult", "dd/d7d/classMagnFieldExtLagMult.html", "dd/d7d/classMagnFieldExtLagMult" ],
    [ "MagnFieldExtX", "d3/df1/classMagnFieldExtX.html", "d3/df1/classMagnFieldExtX" ],
    [ "MagnFieldExtY", "d8/db4/classMagnFieldExtY.html", "d8/db4/classMagnFieldExtY" ],
    [ "MagnFieldExtZ", "d9/d54/classMagnFieldExtZ.html", "d9/d54/classMagnFieldExtZ" ],
    [ "MagnFieldHomAdjX", "d7/d0e/classMagnFieldHomAdjX.html", "d7/d0e/classMagnFieldHomAdjX" ],
    [ "MagnFieldHomAdjY", "d5/d02/classMagnFieldHomAdjY.html", "d5/d02/classMagnFieldHomAdjY" ],
    [ "MagnFieldHomAdjZ", "dd/d95/classMagnFieldHomAdjZ.html", "dd/d95/classMagnFieldHomAdjZ" ],
    [ "MagnFieldHomLagMult", "d7/d29/classMagnFieldHomLagMult.html", "d7/d29/classMagnFieldHomLagMult" ],
    [ "MagnFieldHomLagMultAdj", "de/d4f/classMagnFieldHomLagMultAdj.html", "de/d4f/classMagnFieldHomLagMultAdj" ],
    [ "MagnFieldHomX", "dc/d6c/classMagnFieldHomX.html", "dc/d6c/classMagnFieldHomX" ],
    [ "MagnFieldHomY", "dd/dfc/classMagnFieldHomY.html", "dd/dfc/classMagnFieldHomY" ],
    [ "MagnFieldHomZ", "d4/d88/classMagnFieldHomZ.html", "d4/d88/classMagnFieldHomZ" ],
    [ "Pressure", "d0/d16/classPressure.html", "d0/d16/classPressure" ],
    [ "PressureAdj", "d3/d44/classPressureAdj.html", "d3/d44/classPressureAdj" ],
    [ "Singularity", "d6/d92/classSingularity.html", "d6/d92/classSingularity" ],
    [ "Solution_generation_1", "dd/dc9/classSolution__generation__1.html", "dd/dc9/classSolution__generation__1" ],
    [ "Sphere", "de/d9d/classSphere.html", "de/d9d/classSphere" ],
    [ "Stokes", "d7/d53/PCFieldSplit_2ex6_2ex6_8cpp.html#d2/da8/structStokes", "d7/d53/PCFieldSplit_2ex6_2ex6_8cpp_d2/da8/structStokes" ],
    [ "TempAdj", "db/dfa/classTempAdj.html", "db/dfa/classTempAdj" ],
    [ "Temperature", "d4/d4f/classTemperature.html", "d4/d4f/classTemperature" ],
    [ "TempLift", "d2/d9a/classTempLift.html", "d2/d9a/classTempLift" ],
    [ "VelocityAdjX", "d4/d79/classVelocityAdjX.html", "d4/d79/classVelocityAdjX" ],
    [ "VelocityAdjY", "dc/dbe/classVelocityAdjY.html", "dc/dbe/classVelocityAdjY" ],
    [ "VelocityAdjZ", "db/d63/classVelocityAdjZ.html", "db/d63/classVelocityAdjZ" ],
    [ "VelocityX", "d9/dd3/classVelocityX.html", "d9/dd3/classVelocityX" ],
    [ "VelocityY", "da/d1e/classVelocityY.html", "da/d1e/classVelocityY" ],
    [ "VelocityZ", "dd/d0e/classVelocityZ.html", "dd/d0e/classVelocityZ" ],
    [ "WindowFunction", "dd/d49/classWindowFunction.html", "dd/d49/classWindowFunction" ],
    [ "Zero", "d4/db2/classZero.html", "d4/db2/classZero" ]
];