var annotated_dup =
[
    [ "Domain_L_shaped", "dd/d96/namespace_domain___l__shaped.html", [
      [ "Function_NonZero_on_boundary_2", "da/dee/class_domain___l__shaped_1_1_function___non_zero__on__boundary__2.html", "da/dee/class_domain___l__shaped_1_1_function___non_zero__on__boundary__2" ]
    ] ],
    [ "Domain_square_01by01", "d8/d11/namespace_domain__square__01by01.html", [
      [ "Function_NonZero_on_boundary_1", "d5/d81/class_domain__square__01by01_1_1_function___non_zero__on__boundary__1.html", "d5/d81/class_domain__square__01by01_1_1_function___non_zero__on__boundary__1" ],
      [ "Function_Zero_on_boundary_1", "d8/d94/class_domain__square__01by01_1_1_function___zero__on__boundary__1.html", "d8/d94/class_domain__square__01by01_1_1_function___zero__on__boundary__1" ],
      [ "Function_Zero_on_boundary_2", "da/d57/class_domain__square__01by01_1_1_function___zero__on__boundary__2.html", "da/d57/class_domain__square__01by01_1_1_function___zero__on__boundary__2" ],
      [ "Function_Zero_on_boundary_3", "d7/dda/class_domain__square__01by01_1_1_function___zero__on__boundary__3.html", "d7/dda/class_domain__square__01by01_1_1_function___zero__on__boundary__3" ]
    ] ],
    [ "Domain_square_01by01_Mesh_Distorted", "db/d50/namespace_domain__square__01by01___mesh___distorted.html", [
      [ "Function_Zero_on_boundary_Continuous0_NotC1_1", "df/d61/class_domain__square__01by01___mesh___distorted_1_1_function___zero__on__boundary___continuous0___not_c1__1.html", "df/d61/class_domain__square__01by01___mesh___distorted_1_1_function___zero__on__boundary___continuous0___not_c1__1" ]
    ] ],
    [ "Domain_square_01by01_Mesh_Straight", "d4/d3f/namespace_domain__square__01by01___mesh___straight.html", [
      [ "Function_NonZero_on_boundary_Continuous0_1", "d1/df6/class_domain__square__01by01___mesh___straight_1_1_function___non_zero__on__boundary___continuous0__1.html", "d1/df6/class_domain__square__01by01___mesh___straight_1_1_function___non_zero__on__boundary___continuous0__1" ],
      [ "Function_Zero_on_boundary_Continuous1_1", "dc/d33/class_domain__square__01by01___mesh___straight_1_1_function___zero__on__boundary___continuous1__1.html", "dc/d33/class_domain__square__01by01___mesh___straight_1_1_function___zero__on__boundary___continuous1__1" ]
    ] ],
    [ "Domain_square_m05p05", "d0/d3c/namespace_domain__square__m05p05.html", [
      [ "Function_Zero_on_boundary_4", "de/d5a/class_domain__square__m05p05_1_1_function___zero__on__boundary__4.html", "de/d5a/class_domain__square__m05p05_1_1_function___zero__on__boundary__4" ]
    ] ],
    [ "femus", "d8/dea/namespacefemus.html", [
      [ "ctrl", "dc/dbd/namespacefemus_1_1ctrl.html", [
        [ "boundary_control_between_extreme", "dd/d57/namespacefemus_1_1ctrl_1_1boundary__control__between__extreme.html", [
          [ "cube", "d4/da0/namespacefemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube.html", [
            [ "List_of_Gamma_control_faces_Double", "d0/d00/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___double.html", "d0/d00/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Five", "df/d7b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___five.html", "df/d7b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___five" ],
            [ "List_of_Gamma_control_faces_Four", "df/d9a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four.html", "df/d9a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "dd/d3f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___one.html", "dd/d3f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_Three", "d6/d16/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___three.html", "d6/d16/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d5/d59/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___two.html", "d5/d59/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_One", "d2/dcd/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one.html", "d2/dcd/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "df/df2/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___four.html", "df/df2/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Three", "d7/d40/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___three.html", "d7/d40/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Two", "d8/dc7/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___two.html", "d8/dc7/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Single", "d3/da9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___single.html", "d3/da9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Six", "dc/d78/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___six.html", "dc/d78/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___six" ],
            [ "List_of_Gamma_control_faces_Three", "d3/da4/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three.html", "d3/da4/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "db/d61/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___four.html", "db/d61/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "d6/d18/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___one.html", "d6/d18/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_Two", "db/d70/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___two.html", "db/d70/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Two", "dc/d27/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two.html", "dc/d27/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d6/d9f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___four.html", "d6/d9f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_One", "da/d45/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___one.html", "da/d45/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "d2/df8/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___three.html", "d2/df8/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_list__of___gamma__control__faces___two___three" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "d7/d99/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1cube_1_1_multiple__controls__and__hf246a5d96c0371b0dfd1a7f28d8926f1.html", null ]
          ] ],
          [ "square", "d9/d67/namespacefemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square.html", [
            [ "Boundary_Condition_control_between_extreme", "d6/d02/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_boundary___condition__control__between__extreme.html", "d6/d02/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_boundary___condition__control__between__extreme" ],
            [ "Double_controls_adjacent_in_front_linear", "d9/d11/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_double__controls__adjacent__in__front__linear.html", "d9/d11/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_double__controls__adjacent__in__front__linear" ],
            [ "List_of_Gamma_control_faces_Double", "d4/db5/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___double.html", "d4/db5/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Four", "da/de0/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four.html", "da/de0/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "db/d77/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one.html", "db/d77/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_One_Three", "d5/dc6/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___three.html", "d5/dc6/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___three" ],
            [ "List_of_Gamma_control_faces_Four_One_Two", "dc/d95/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___two.html", "dc/d95/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "df/de9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___three.html", "df/de9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d2/d9e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two.html", "d2/d9e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_Four_Two_Three", "d4/d13/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two___three.html", "d4/d13/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two___three" ],
            [ "List_of_Gamma_control_faces_One", "da/dbc/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one.html", "da/dbc/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "d2/d60/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four.html", "d2/d60/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Four_Three", "dd/d91/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___three.html", "dd/d91/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___three" ],
            [ "List_of_Gamma_control_faces_One_Four_Two", "d6/dcb/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___two.html", "d6/dcb/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___four___two" ],
            [ "List_of_Gamma_control_faces_One_Three", "d0/d2c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three.html", "d0/d2c/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Three_Four", "d3/d24/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___four.html", "d3/d24/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___four" ],
            [ "List_of_Gamma_control_faces_One_Three_Two", "d7/d4f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___two.html", "d7/d4f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___three___two" ],
            [ "List_of_Gamma_control_faces_One_Three_Two_Four", "d9/d16/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__controb8d795ffe0db3c54a4be746b7d52b5a9.html", "d9/d16/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__controb8d795ffe0db3c54a4be746b7d52b5a9" ],
            [ "List_of_Gamma_control_faces_One_Two", "d7/def/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___two.html", "d7/def/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Quadruple", "d6/d9f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___quadruple.html", "d6/d9f/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___quadruple" ],
            [ "List_of_Gamma_control_faces_Single", "d3/dac/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___single.html", "d3/dac/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Three", "df/d4a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three.html", "df/d4a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "d0/d39/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___four.html", "d0/d39/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "d4/ddd/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one.html", "d4/ddd/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_One_Four", "d8/db4/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___four.html", "d8/db4/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___four" ],
            [ "List_of_Gamma_control_faces_Three_One_Two", "d7/df9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___two.html", "d7/df9/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___one___two" ],
            [ "List_of_Gamma_control_faces_Three_Two", "dd/d20/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two.html", "dd/d20/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Three_Two_Four", "d2/d88/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___four.html", "d2/d88/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___four" ],
            [ "List_of_Gamma_control_faces_Three_Two_One", "d3/d00/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___one.html", "d3/d00/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___three___two___one" ],
            [ "List_of_Gamma_control_faces_Triple", "d1/d11/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___triple.html", "d1/d11/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___triple" ],
            [ "List_of_Gamma_control_faces_Two", "d2/d69/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two.html", "d2/d69/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d9/d65/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four.html", "d9/d65/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_Four_One", "db/d2b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___one.html", "db/d2b/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___one" ],
            [ "List_of_Gamma_control_faces_Two_Four_Three", "d2/d0e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___three.html", "d2/d0e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___four___three" ],
            [ "List_of_Gamma_control_faces_Two_One", "dd/d4a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___one.html", "dd/d4a/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "d1/d19/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three.html", "d1/d19/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three" ],
            [ "List_of_Gamma_control_faces_Two_Three_Four", "d7/dff/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___four.html", "d7/dff/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___four" ],
            [ "List_of_Gamma_control_faces_Two_Three_One", "da/d7e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___one.html", "da/d7e/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___two___three___one" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "d4/d52/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__and_b461cb5d81624a4feb17a56b9e0453e1.html", "d4/d52/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__and_b461cb5d81624a4feb17a56b9e0453e1" ],
            [ "Multiple_controls_in_front_constant", "d2/dba/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__in__front__constant.html", "d2/dba/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_multiple__controls__in__front__constant" ],
            [ "Single_control_in_front_linear", "dd/d02/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_single__control__in__front__linear.html", "dd/d02/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_single__control__in__front__linear" ],
            [ "Triple_controls_adjacent_in_front_linear", "d0/dfa/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_triple__controls__adjacent__in__front__linear.html", "d0/dfa/classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_triple__controls__adjacent__in__front__linear" ]
          ] ]
        ] ],
        [ "boundary_control_full_face", "d4/d1c/namespacefemus_1_1ctrl_1_1boundary__control__full__face.html", [
          [ "cube", "db/d4a/namespacefemus_1_1ctrl_1_1boundary__control__full__face_1_1cube.html", [
            [ "List_of_Gamma_control_faces_Double", "d5/d3b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___double.html", "d5/d3b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Five", "d0/df5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___five.html", "d0/df5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___five" ],
            [ "List_of_Gamma_control_faces_Four", "d4/db5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four.html", "d4/db5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "de/daa/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___one.html", "de/daa/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_Three", "d5/dea/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___three.html", "d5/dea/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d2/d5f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___two.html", "d2/d5f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_One", "d3/d20/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one.html", "d3/d20/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "d8/d4c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___four.html", "d8/d4c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Three", "d2/df1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___three.html", "d2/df1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Two", "dd/d8b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___two.html", "dd/d8b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Single", "d5/d8d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___single.html", "d5/d8d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Six", "d5/d6a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___six.html", "d5/d6a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___six" ],
            [ "List_of_Gamma_control_faces_Three", "d6/dfb/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three.html", "d6/dfb/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "d0/d7d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___four.html", "d0/d7d/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "d6/dd5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___one.html", "d6/dd5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_Two", "da/d60/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___two.html", "da/d60/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Two", "dd/d8f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two.html", "dd/d8f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d3/d68/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___four.html", "d3/d68/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_One", "d9/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___one.html", "d9/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "d8/d7f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___three.html", "d8/d7f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1cube_1_1_list__of___gamma__control__faces___two___three" ]
          ] ],
          [ "square", "d1/df1/namespacefemus_1_1ctrl_1_1boundary__control__full__face_1_1square.html", [
            [ "Boundary_Condition_control_full_face", "db/d68/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_boundary___condition__control__full__face.html", "db/d68/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_boundary___condition__control__full__face" ],
            [ "Double_controls_adjacent_in_front_linear", "d0/d02/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_double__controls__adjacent__in__front__linear.html", "d0/d02/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_double__controls__adjacent__in__front__linear" ],
            [ "List_of_Gamma_control_faces_Double", "dd/da6/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___double.html", "dd/da6/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___double" ],
            [ "List_of_Gamma_control_faces_Four", "dd/dce/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four.html", "dd/dce/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four" ],
            [ "List_of_Gamma_control_faces_Four_One", "db/ddc/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one.html", "db/ddc/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one" ],
            [ "List_of_Gamma_control_faces_Four_One_Three", "d9/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___three.html", "d9/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___three" ],
            [ "List_of_Gamma_control_faces_Four_One_Two", "dd/d6b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___two.html", "dd/d6b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___one___two" ],
            [ "List_of_Gamma_control_faces_Four_Three", "df/d9b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___three.html", "df/d9b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___three" ],
            [ "List_of_Gamma_control_faces_Four_Two", "d9/d94/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two.html", "d9/d94/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two" ],
            [ "List_of_Gamma_control_faces_Four_Two_Three", "d2/dd4/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two___three.html", "d2/dd4/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___four___two___three" ],
            [ "List_of_Gamma_control_faces_One", "d2/da9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one.html", "d2/da9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one" ],
            [ "List_of_Gamma_control_faces_One_Four", "dc/d2f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four.html", "dc/d2f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four" ],
            [ "List_of_Gamma_control_faces_One_Four_Three", "df/d4b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___three.html", "df/d4b/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___three" ],
            [ "List_of_Gamma_control_faces_One_Four_Two", "d7/d1c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___two.html", "d7/d1c/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___four___two" ],
            [ "List_of_Gamma_control_faces_One_Three", "d1/db9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three.html", "d1/db9/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three" ],
            [ "List_of_Gamma_control_faces_One_Three_Four", "d5/d14/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___four.html", "d5/d14/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___four" ],
            [ "List_of_Gamma_control_faces_One_Three_Two", "dc/dac/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two.html", "dc/dac/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two" ],
            [ "List_of_Gamma_control_faces_One_Three_Two_Four", "d6/d2e/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two___four.html", "d6/d2e/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___three___two___four" ],
            [ "List_of_Gamma_control_faces_One_Two", "d8/da1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___two.html", "d8/da1/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___one___two" ],
            [ "List_of_Gamma_control_faces_Quadruple", "d4/dc6/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___quadruple.html", "d4/dc6/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___quadruple" ],
            [ "List_of_Gamma_control_faces_Single", "de/dc8/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___single.html", "de/dc8/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___single" ],
            [ "List_of_Gamma_control_faces_Three", "d7/d62/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three.html", "d7/d62/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three" ],
            [ "List_of_Gamma_control_faces_Three_Four", "d3/d7e/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___four.html", "d3/d7e/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___four" ],
            [ "List_of_Gamma_control_faces_Three_One", "d9/d34/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one.html", "d9/d34/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one" ],
            [ "List_of_Gamma_control_faces_Three_One_Four", "d9/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___four.html", "d9/d33/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___four" ],
            [ "List_of_Gamma_control_faces_Three_One_Two", "d9/df4/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___two.html", "d9/df4/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___one___two" ],
            [ "List_of_Gamma_control_faces_Three_Two", "db/de5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two.html", "db/de5/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two" ],
            [ "List_of_Gamma_control_faces_Three_Two_Four", "db/da7/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___four.html", "db/da7/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___four" ],
            [ "List_of_Gamma_control_faces_Three_Two_One", "dc/d11/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___one.html", "dc/d11/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___three___two___one" ],
            [ "List_of_Gamma_control_faces_Triple", "dc/d55/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___triple.html", "dc/d55/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___triple" ],
            [ "List_of_Gamma_control_faces_Two", "d6/d8f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two.html", "d6/d8f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two" ],
            [ "List_of_Gamma_control_faces_Two_Four", "d0/d14/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four.html", "d0/d14/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four" ],
            [ "List_of_Gamma_control_faces_Two_Four_One", "d4/dea/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___one.html", "d4/dea/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___one" ],
            [ "List_of_Gamma_control_faces_Two_Four_Three", "dc/d4f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___three.html", "dc/d4f/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___four___three" ],
            [ "List_of_Gamma_control_faces_Two_One", "de/d60/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___one.html", "de/d60/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___one" ],
            [ "List_of_Gamma_control_faces_Two_Three", "dd/dde/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three.html", "dd/dde/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three" ],
            [ "List_of_Gamma_control_faces_Two_Three_Four", "dc/d52/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___four.html", "dc/d52/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___four" ],
            [ "List_of_Gamma_control_faces_Two_Three_One", "d1/dfe/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___one.html", "d1/dfe/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_list__of___gamma__control__faces___two___three___one" ],
            [ "Multiple_controls_and_homogeneous_boundary_conditions", "d9/dfa/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__and__homogeneous__boundary__conditions.html", "d9/dfa/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__and__homogeneous__boundary__conditions" ],
            [ "Multiple_controls_in_front_constant", "dd/d30/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__in__front__constant.html", "dd/d30/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_multiple__controls__in__front__constant" ],
            [ "Single_control_in_front_linear", "db/d6a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_single__control__in__front__linear.html", "db/d6a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_single__control__in__front__linear" ],
            [ "Triple_controls_adjacent_in_front_linear", "d9/d7a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_triple__controls__adjacent__in__front__linear.html", "d9/d7a/classfemus_1_1ctrl_1_1boundary__control__full__face_1_1square_1_1_triple__controls__adjacent__in__front__linear" ]
          ] ]
        ] ],
        [ "cube", "df/dfc/namespacefemus_1_1ctrl_1_1cube.html", [
          [ "cost_functional_without_regularization", "dd/d03/classfemus_1_1ctrl_1_1cube_1_1cost__functional__without__regularization.html", null ]
        ] ],
        [ "square", "d1/d71/namespacefemus_1_1ctrl_1_1square.html", [
          [ "cost_functional_without_regularization", "d1/dc7/classfemus_1_1ctrl_1_1square_1_1cost__functional__without__regularization.html", null ]
        ] ],
        [ "square_or_cube", "db/dec/namespacefemus_1_1ctrl_1_1square__or__cube.html", [
          [ "Boundary_Condition", "dd/ded/classfemus_1_1ctrl_1_1square__or__cube_1_1_boundary___condition.html", "dd/ded/classfemus_1_1ctrl_1_1square__or__cube_1_1_boundary___condition" ],
          [ "cost_functional_without_regularization", "dd/d48/classfemus_1_1ctrl_1_1square__or__cube_1_1cost__functional__without__regularization.html", "dd/d48/classfemus_1_1ctrl_1_1square__or__cube_1_1cost__functional__without__regularization" ],
          [ "Domain_elements_containing_Gamma_control", "dc/d03/classfemus_1_1ctrl_1_1square__or__cube_1_1_domain__elements__containing___gamma__control.html", null ],
          [ "lifting_external", "d2/da1/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__external.html", "d2/da1/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__external" ],
          [ "lifting_internal", "d7/d7b/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__internal.html", "d7/d7b/classfemus_1_1ctrl_1_1square__or__cube_1_1lifting__internal" ],
          [ "List_of_faces", "d2/d6f/classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of__faces.html", "d2/d6f/classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of__faces" ],
          [ "List_of_Gamma_control_faces", "d2/d9b/classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of___gamma__control__faces.html", "d2/d9b/classfemus_1_1ctrl_1_1square__or__cube_1_1_list__of___gamma__control__faces" ],
          [ "mixed_state_or_ctrl_inequality", "d9/ddd/classfemus_1_1ctrl_1_1square__or__cube_1_1mixed__state__or__ctrl__inequality.html", "d9/ddd/classfemus_1_1ctrl_1_1square__or__cube_1_1mixed__state__or__ctrl__inequality" ],
          [ "pure_boundary", "de/db9/classfemus_1_1ctrl_1_1square__or__cube_1_1pure__boundary.html", "de/db9/classfemus_1_1ctrl_1_1square__or__cube_1_1pure__boundary" ]
        ] ],
        [ "cost_functional", "d0/dec/classfemus_1_1ctrl_1_1cost__functional.html", "d0/dec/classfemus_1_1ctrl_1_1cost__functional" ],
        [ "cost_functional_without_regularization", "d0/dc3/classfemus_1_1ctrl_1_1cost__functional__without__regularization.html", null ],
        [ "Domain_of_PDE", "de/d51/classfemus_1_1ctrl_1_1_domain__of___p_d_e.html", "de/d51/classfemus_1_1ctrl_1_1_domain__of___p_d_e" ],
        [ "Gamma_control_equation_fractional_sobolev_differentiability_index", "d8/d67/classfemus_1_1ctrl_1_1_gamma__control__equation__fractional__sobolev__differentiability__index.html", "d8/d67/classfemus_1_1ctrl_1_1_gamma__control__equation__fractional__sobolev__differentiability__index" ],
        [ "Gamma_control_equation_integer_sobolev_differentiability_index", "d0/d9e/classfemus_1_1ctrl_1_1_gamma__control__equation__integer__sobolev__differentiability__index.html", "d0/d9e/classfemus_1_1ctrl_1_1_gamma__control__equation__integer__sobolev__differentiability__index" ],
        [ "mixed_state_or_ctrl_inequality", "d2/dd1/classfemus_1_1ctrl_1_1mixed__state__or__ctrl__inequality.html", "d2/dd1/classfemus_1_1ctrl_1_1mixed__state__or__ctrl__inequality" ]
      ] ],
      [ "elliptic", "df/d9f/namespacefemus_1_1elliptic.html", [
        [ "lifting_external", "d7/d9a/classfemus_1_1elliptic_1_1lifting__external.html", "d7/d9a/classfemus_1_1elliptic_1_1lifting__external" ],
        [ "lifting_internal", "d8/dea/classfemus_1_1elliptic_1_1lifting__internal.html", "d8/dea/classfemus_1_1elliptic_1_1lifting__internal" ],
        [ "pure_boundary", "dd/d57/classfemus_1_1elliptic_1_1pure__boundary.html", "dd/d57/classfemus_1_1elliptic_1_1pure__boundary" ]
      ] ],
      [ "Math", "d0/d3b/namespacefemus_1_1_math.html", [
        [ "Function", "da/d19/classfemus_1_1_math_1_1_function.html", "da/d19/classfemus_1_1_math_1_1_function" ]
      ] ],
      [ "navier_stokes", "d3/de9/namespacefemus_1_1navier__stokes.html", [
        [ "lifting_internal", "d2/dc8/classfemus_1_1navier__stokes_1_1lifting__internal.html", "d2/dc8/classfemus_1_1navier__stokes_1_1lifting__internal" ],
        [ "pure_boundary", "d1/d8e/classfemus_1_1navier__stokes_1_1pure__boundary.html", "d1/d8e/classfemus_1_1navier__stokes_1_1pure__boundary" ]
      ] ],
      [ "Parallel", "db/ded/namespacefemus_1_1_parallel.html", [
        [ "data_type", "db/ded/namespacefemus_1_1_parallel.html#de/df4/structfemus_1_1_parallel_1_1data__type", null ],
        [ "DataType", "d9/d74/classfemus_1_1_parallel_1_1_data_type.html", "d9/d74/classfemus_1_1_parallel_1_1_data_type" ],
        [ "request", "db/ded/namespacefemus_1_1_parallel.html#d8/dfd/structfemus_1_1_parallel_1_1request", null ],
        [ "Request", "dc/d13/classfemus_1_1_parallel_1_1_request.html", "dc/d13/classfemus_1_1_parallel_1_1_request" ],
        [ "status", "db/ded/namespacefemus_1_1_parallel.html#d8/d6c/structfemus_1_1_parallel_1_1status", null ],
        [ "Status", "d1/d0e/classfemus_1_1_parallel_1_1_status.html", "d1/d0e/classfemus_1_1_parallel_1_1_status" ]
      ] ],
      [ "app_specifics", "dd/d15/classfemus_1_1app__specifics.html", "dd/d15/classfemus_1_1app__specifics" ],
      [ "assemble_jacobian", "d4/d7a/classfemus_1_1assemble__jacobian.html", "d4/d7a/classfemus_1_1assemble__jacobian" ],
      [ "basis", "dc/d77/classfemus_1_1basis.html", "dc/d77/classfemus_1_1basis" ],
      [ "BoundaryConditions", "d4/db4/classfemus_1_1_boundary_conditions.html", "d4/db4/classfemus_1_1_boundary_conditions" ],
      [ "Box", "da/d8d/classfemus_1_1_box.html", "da/d8d/classfemus_1_1_box" ],
      [ "CurrentElem", "d4/d0f/classfemus_1_1_current_elem.html", "d4/d0f/classfemus_1_1_current_elem" ],
      [ "CurrentQuantity", "de/d6e/classfemus_1_1_current_quantity.html", "de/d6e/classfemus_1_1_current_quantity" ],
      [ "DenseMatrix", "d9/db3/classfemus_1_1_dense_matrix.html", "d9/db3/classfemus_1_1_dense_matrix" ],
      [ "DenseMatrixBase", "df/d78/classfemus_1_1_dense_matrix_base.html", "df/d78/classfemus_1_1_dense_matrix_base" ],
      [ "DenseSubMatrix", "d7/dbc/classfemus_1_1_dense_sub_matrix.html", "d7/dbc/classfemus_1_1_dense_sub_matrix" ],
      [ "DenseSubVector", "dd/d6a/classfemus_1_1_dense_sub_vector.html", "dd/d6a/classfemus_1_1_dense_sub_vector" ],
      [ "DenseVector", "d7/de8/classfemus_1_1_dense_vector.html", "d7/de8/classfemus_1_1_dense_vector" ],
      [ "DenseVectorBase", "d6/dea/classfemus_1_1_dense_vector_base.html", "d6/dea/classfemus_1_1_dense_vector_base" ],
      [ "DofMap", "d2/d84/classfemus_1_1_dof_map.html", "d2/d84/classfemus_1_1_dof_map" ],
      [ "Domain", "dc/d19/classfemus_1_1_domain.html", "dc/d19/classfemus_1_1_domain" ],
      [ "elem", "db/d2e/classfemus_1_1elem.html", "db/d2e/classfemus_1_1elem" ],
      [ "elem_type", "d3/dca/classfemus_1_1elem__type.html", "d3/dca/classfemus_1_1elem__type" ],
      [ "elem_type_1D", "d9/dd6/classfemus_1_1elem__type__1_d.html", "d9/dd6/classfemus_1_1elem__type__1_d" ],
      [ "elem_type_2D", "d9/d52/classfemus_1_1elem__type__2_d.html", "d9/d52/classfemus_1_1elem__type__2_d" ],
      [ "elem_type_3D", "d0/d2c/classfemus_1_1elem__type__3_d.html", "d0/d2c/classfemus_1_1elem__type__3_d" ],
      [ "elem_type_templ", "d6/dcf/classfemus_1_1elem__type__templ.html", "d6/dcf/classfemus_1_1elem__type__templ" ],
      [ "elem_type_templ< type, type_mov, 1, 3 >", "d8/d15/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_011_00_013_01_4.html", "d8/d15/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_011_00_013_01_4" ],
      [ "elem_type_templ< type, type_mov, 2, 3 >", "d1/dda/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_012_00_013_01_4.html", "d1/dda/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_012_00_013_01_4" ],
      [ "elem_type_templ< type, type_mov, 3, 3 >", "d9/df4/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_013_00_013_01_4.html", "d9/df4/classfemus_1_1elem__type__templ_3_01type_00_01type__mov_00_013_00_013_01_4" ],
      [ "elem_type_templ_base", "da/ddf/classfemus_1_1elem__type__templ__base.html", "da/ddf/classfemus_1_1elem__type__templ__base" ],
      [ "ElementJacRes", "d3/dc6/classfemus_1_1_element_jac_res.html", "d3/dc6/classfemus_1_1_element_jac_res" ],
      [ "ElemStoBase", "d4/df9/classfemus_1_1_elem_sto_base.html", "d4/df9/classfemus_1_1_elem_sto_base" ],
      [ "ElemStoBdry", "d4/d13/classfemus_1_1_elem_sto_bdry.html", "d4/d13/classfemus_1_1_elem_sto_bdry" ],
      [ "ElemStoVol", "d2/dd4/classfemus_1_1_elem_sto_vol.html", "d2/dd4/classfemus_1_1_elem_sto_vol" ],
      [ "ExplicitSystem", "da/da1/classfemus_1_1_explicit_system.html", "da/da1/classfemus_1_1_explicit_system" ],
      [ "FE_convergence", "d4/da0/classfemus_1_1_f_e__convergence.html", "d4/da0/classfemus_1_1_f_e__convergence" ],
      [ "FemusInit", "da/d5e/classfemus_1_1_femus_init.html", "da/d5e/classfemus_1_1_femus_init" ],
      [ "FemusInputParser", "d5/dbd/classfemus_1_1_femus_input_parser.html", "d5/dbd/classfemus_1_1_femus_input_parser" ],
      [ "FieldSplitTree", "d9/d1f/classfemus_1_1_field_split_tree.html", "d9/d1f/classfemus_1_1_field_split_tree" ],
      [ "Files", "d6/d0b/classfemus_1_1_files.html", "d6/d0b/classfemus_1_1_files" ],
      [ "Fluid", "d8/d4e/classfemus_1_1_fluid.html", "d8/d4e/classfemus_1_1_fluid" ],
      [ "FunctionBase", "d9/d62/classfemus_1_1_function_base.html", "d9/d62/classfemus_1_1_function_base" ],
      [ "GambitIO", "da/dc6/classfemus_1_1_gambit_i_o.html", "da/dc6/classfemus_1_1_gambit_i_o" ],
      [ "Gauss", "db/db8/classfemus_1_1_gauss.html", "db/db8/classfemus_1_1_gauss" ],
      [ "GenCase", "d5/dc2/classfemus_1_1_gen_case.html", "d5/dc2/classfemus_1_1_gen_case" ],
      [ "GeomElemBase", "de/deb/classfemus_1_1_geom_elem_base.html", "de/deb/classfemus_1_1_geom_elem_base" ],
      [ "GeomElemEdge2", "dd/dd0/classfemus_1_1_geom_elem_edge2.html", "dd/dd0/classfemus_1_1_geom_elem_edge2" ],
      [ "GeomElemEdge3", "da/d14/classfemus_1_1_geom_elem_edge3.html", "da/d14/classfemus_1_1_geom_elem_edge3" ],
      [ "GeomElemHex27", "dc/d8a/classfemus_1_1_geom_elem_hex27.html", "dc/d8a/classfemus_1_1_geom_elem_hex27" ],
      [ "GeomElemHex8", "d6/d2f/classfemus_1_1_geom_elem_hex8.html", "d6/d2f/classfemus_1_1_geom_elem_hex8" ],
      [ "GeomElemQuad4", "d7/db8/classfemus_1_1_geom_elem_quad4.html", "d7/db8/classfemus_1_1_geom_elem_quad4" ],
      [ "GeomElemQuad9", "df/d03/classfemus_1_1_geom_elem_quad9.html", "df/d03/classfemus_1_1_geom_elem_quad9" ],
      [ "GeomElemTet10", "d4/d05/classfemus_1_1_geom_elem_tet10.html", "d4/d05/classfemus_1_1_geom_elem_tet10" ],
      [ "GeomElemTet4", "d2/dd1/classfemus_1_1_geom_elem_tet4.html", "d2/dd1/classfemus_1_1_geom_elem_tet4" ],
      [ "GeomElemTri3", "d8/db7/classfemus_1_1_geom_elem_tri3.html", "d8/db7/classfemus_1_1_geom_elem_tri3" ],
      [ "GeomElemTri6", "d0/d80/classfemus_1_1_geom_elem_tri6.html", "d0/d80/classfemus_1_1_geom_elem_tri6" ],
      [ "GeomElemTri7", "de/ddd/classfemus_1_1_geom_elem_tri7.html", "de/ddd/classfemus_1_1_geom_elem_tri7" ],
      [ "GMVWriter", "d1/d28/classfemus_1_1_g_m_v_writer.html", "d1/d28/classfemus_1_1_g_m_v_writer" ],
      [ "Graph", "d0/def/classfemus_1_1_graph.html", "d0/def/classfemus_1_1_graph" ],
      [ "Gravity", "d9/daf/classfemus_1_1_gravity.html", "d9/daf/classfemus_1_1_gravity" ],
      [ "hex0", "db/dd3/classfemus_1_1hex0.html", "db/dd3/classfemus_1_1hex0" ],
      [ "hex_const", "d2/d21/classfemus_1_1hex__const.html", "d2/d21/classfemus_1_1hex__const" ],
      [ "hex_gauss", "d8/d5a/classfemus_1_1hex__gauss.html", "d8/d5a/classfemus_1_1hex__gauss" ],
      [ "hex_lag", "d9/d7c/classfemus_1_1hex__lag.html", "d9/d7c/classfemus_1_1hex__lag" ],
      [ "HexBiquadratic", "dc/d23/classfemus_1_1_hex_biquadratic.html", "dc/d23/classfemus_1_1_hex_biquadratic" ],
      [ "HexLinear", "d1/d1a/classfemus_1_1_hex_linear.html", "d1/d1a/classfemus_1_1_hex_linear" ],
      [ "hexpwLinear", "d9/d51/classfemus_1_1hexpw_linear.html", "d9/d51/classfemus_1_1hexpw_linear" ],
      [ "HexQuadratic", "db/df4/classfemus_1_1_hex_quadratic.html", "db/df4/classfemus_1_1_hex_quadratic" ],
      [ "HtmlInputParser", "d6/d38/classfemus_1_1_html_input_parser.html", "d6/d38/classfemus_1_1_html_input_parser" ],
      [ "ImplicitRungeKuttaSystem", "d3/d41/classfemus_1_1_implicit_runge_kutta_system.html", "d3/d41/classfemus_1_1_implicit_runge_kutta_system" ],
      [ "ImplicitSystem", "dc/d6c/classfemus_1_1_implicit_system.html", "dc/d6c/classfemus_1_1_implicit_system" ],
      [ "InputParser", "da/d52/classfemus_1_1_input_parser.html", "da/d52/classfemus_1_1_input_parser" ],
      [ "JsonInputParser", "dc/ded/classfemus_1_1_json_input_parser.html", "dc/ded/classfemus_1_1_json_input_parser" ],
      [ "lifting_external", "de/da3/classfemus_1_1lifting__external.html", "de/da3/classfemus_1_1lifting__external" ],
      [ "lifting_internal", "d7/d2f/classfemus_1_1lifting__internal.html", "d7/d2f/classfemus_1_1lifting__internal" ],
      [ "Line", "dc/d42/classfemus_1_1_line.html", "dc/d42/classfemus_1_1_line" ],
      [ "line0", "d7/d9a/classfemus_1_1line0.html", "d7/d9a/classfemus_1_1line0" ],
      [ "line_const", "da/d3d/classfemus_1_1line__const.html", "da/d3d/classfemus_1_1line__const" ],
      [ "line_gauss", "d9/d01/classfemus_1_1line__gauss.html", "d9/d01/classfemus_1_1line__gauss" ],
      [ "line_lag", "dd/da8/classfemus_1_1line__lag.html", "dd/da8/classfemus_1_1line__lag" ],
      [ "LinearEquation", "da/de0/classfemus_1_1_linear_equation.html", "da/de0/classfemus_1_1_linear_equation" ],
      [ "LinearEquationSolver", "da/d1a/classfemus_1_1_linear_equation_solver.html", "da/d1a/classfemus_1_1_linear_equation_solver" ],
      [ "LinearEquationSolverPetsc", "dd/de2/classfemus_1_1_linear_equation_solver_petsc.html", "dd/de2/classfemus_1_1_linear_equation_solver_petsc" ],
      [ "LinearEquationSolverPetscAsm", "de/d5a/classfemus_1_1_linear_equation_solver_petsc_asm.html", "de/d5a/classfemus_1_1_linear_equation_solver_petsc_asm" ],
      [ "LinearEquationSolverPetscFieldSplit", "dd/dfa/classfemus_1_1_linear_equation_solver_petsc_field_split.html", "dd/dfa/classfemus_1_1_linear_equation_solver_petsc_field_split" ],
      [ "LinearImplicitSystem", "d8/d4a/classfemus_1_1_linear_implicit_system.html", "d8/d4a/classfemus_1_1_linear_implicit_system" ],
      [ "LineBiquadratic", "dd/d64/classfemus_1_1_line_biquadratic.html", "dd/d64/classfemus_1_1_line_biquadratic" ],
      [ "LineLinear", "d4/ddc/classfemus_1_1_line_linear.html", "d4/ddc/classfemus_1_1_line_linear" ],
      [ "linepwLinear", "dd/d7a/classfemus_1_1linepw_linear.html", "dd/d7a/classfemus_1_1linepw_linear" ],
      [ "Marker", "d9/db8/classfemus_1_1_marker.html", "d9/db8/classfemus_1_1_marker" ],
      [ "Material", "d0/d38/classfemus_1_1_material.html", "d0/d38/classfemus_1_1_material" ],
      [ "Mesh", "d9/d8b/classfemus_1_1_mesh.html", "d9/d8b/classfemus_1_1_mesh" ],
      [ "MeshASMPartitioning", "d9/d81/classfemus_1_1_mesh_a_s_m_partitioning.html", "d9/d81/classfemus_1_1_mesh_a_s_m_partitioning" ],
      [ "MeshInput", "df/d9c/classfemus_1_1_mesh_input.html", "df/d9c/classfemus_1_1_mesh_input" ],
      [ "MeshMetisPartitioning", "da/de8/classfemus_1_1_mesh_metis_partitioning.html", "da/de8/classfemus_1_1_mesh_metis_partitioning" ],
      [ "MeshPartitioning", "dc/dca/classfemus_1_1_mesh_partitioning.html", "dc/dca/classfemus_1_1_mesh_partitioning" ],
      [ "MeshRefinement", "d5/de8/classfemus_1_1_mesh_refinement.html", "d5/de8/classfemus_1_1_mesh_refinement" ],
      [ "MonolithicFSINonLinearImplicitSystem", "d1/d93/classfemus_1_1_monolithic_f_s_i_non_linear_implicit_system.html", "d1/d93/classfemus_1_1_monolithic_f_s_i_non_linear_implicit_system" ],
      [ "MultiLevelMesh", "dc/d8d/classfemus_1_1_multi_level_mesh.html", "dc/d8d/classfemus_1_1_multi_level_mesh" ],
      [ "MultiLevelMeshTwo", "d9/d52/classfemus_1_1_multi_level_mesh_two.html", "d9/d52/classfemus_1_1_multi_level_mesh_two" ],
      [ "MultiLevelProblem", "de/d6a/classfemus_1_1_multi_level_problem.html", "de/d6a/classfemus_1_1_multi_level_problem" ],
      [ "MultiLevelSolution", "d6/da4/classfemus_1_1_multi_level_solution.html", "d6/da4/classfemus_1_1_multi_level_solution" ],
      [ "MyMatrix", "d1/d82/classfemus_1_1_my_matrix.html", "d1/d82/classfemus_1_1_my_matrix" ],
      [ "MyVector", "d7/d8c/classfemus_1_1_my_vector.html", "d7/d8c/classfemus_1_1_my_vector" ],
      [ "NewmarkTransientSystem", "dc/d9e/classfemus_1_1_newmark_transient_system.html", "dc/d9e/classfemus_1_1_newmark_transient_system" ],
      [ "NodeSto", "d8/d4d/classfemus_1_1_node_sto.html", "d8/d4d/classfemus_1_1_node_sto" ],
      [ "NonLinearImplicitSystem", "dd/d33/classfemus_1_1_non_linear_implicit_system.html", "dd/d33/classfemus_1_1_non_linear_implicit_system" ],
      [ "NonLinearImplicitSystemWithPrimalDualActiveSetMethod", "d1/d09/classfemus_1_1_non_linear_implicit_system_with_primal_dual_active_set_method.html", "d1/d09/classfemus_1_1_non_linear_implicit_system_with_primal_dual_active_set_method" ],
      [ "NumericVector", "da/d12/classfemus_1_1_numeric_vector.html", "da/d12/classfemus_1_1_numeric_vector" ],
      [ "OptLoop", "d6/d47/classfemus_1_1_opt_loop.html", "d6/d47/classfemus_1_1_opt_loop" ],
      [ "ParallelObject", "dd/d90/classfemus_1_1_parallel_object.html", "dd/d90/classfemus_1_1_parallel_object" ],
      [ "Parameter", "d7/d3c/classfemus_1_1_parameter.html", "d7/d3c/classfemus_1_1_parameter" ],
      [ "Parameters", "d4/de5/classfemus_1_1_parameters.html", "d4/de5/classfemus_1_1_parameters" ],
      [ "ParsedFunction", "d8/de4/classfemus_1_1_parsed_function.html", "d8/de4/classfemus_1_1_parsed_function" ],
      [ "PetscMatrix", "da/dcf/classfemus_1_1_petsc_matrix.html", "da/dcf/classfemus_1_1_petsc_matrix" ],
      [ "PetscPreconditioner", "d4/d01/classfemus_1_1_petsc_preconditioner.html", "d4/d01/classfemus_1_1_petsc_preconditioner" ],
      [ "PetscVector", "d2/d9c/classfemus_1_1_petsc_vector.html", "d2/d9c/classfemus_1_1_petsc_vector" ],
      [ "Phi", "dd/d8f/classfemus_1_1_phi.html", "dd/d8f/classfemus_1_1_phi" ],
      [ "point_gauss", "de/d84/classfemus_1_1point__gauss.html", "de/d84/classfemus_1_1point__gauss" ],
      [ "poisson_equation", "d5/dbd/classfemus_1_1poisson__equation.html", "d5/dbd/classfemus_1_1poisson__equation" ],
      [ "Preconditioner", "d9/d80/classfemus_1_1_preconditioner.html", "d9/d80/classfemus_1_1_preconditioner" ],
      [ "pure_boundary", "df/dfc/classfemus_1_1pure__boundary.html", "df/dfc/classfemus_1_1pure__boundary" ],
      [ "quad0", "d5/dca/classfemus_1_1quad0.html", "d5/dca/classfemus_1_1quad0" ],
      [ "quad_const", "d9/d6e/classfemus_1_1quad__const.html", "d9/d6e/classfemus_1_1quad__const" ],
      [ "quad_gauss", "d2/d99/classfemus_1_1quad__gauss.html", "d2/d99/classfemus_1_1quad__gauss" ],
      [ "quad_lag", "d3/db3/classfemus_1_1quad__lag.html", "d3/db3/classfemus_1_1quad__lag" ],
      [ "QuadBiquadratic", "dc/db0/classfemus_1_1_quad_biquadratic.html", "dc/db0/classfemus_1_1_quad_biquadratic" ],
      [ "QuadLinear", "d5/d2e/classfemus_1_1_quad_linear.html", "d5/d2e/classfemus_1_1_quad_linear" ],
      [ "quadpwLinear", "d9/db8/classfemus_1_1quadpw_linear.html", "d9/db8/classfemus_1_1quadpw_linear" ],
      [ "QuadQuadratic", "d8/d9e/classfemus_1_1_quad_quadratic.html", "d8/d9e/classfemus_1_1_quad_quadratic" ],
      [ "Quantity", "d8/d5a/classfemus_1_1_quantity.html", "d8/d5a/classfemus_1_1_quantity" ],
      [ "QuantityMap", "d5/d5a/classfemus_1_1_quantity_map.html", "d5/d5a/classfemus_1_1_quantity_map" ],
      [ "Solid", "d8/d1a/classfemus_1_1_solid.html", "d8/d1a/classfemus_1_1_solid" ],
      [ "Solution", "d4/d40/classfemus_1_1_solution.html", "d4/d40/classfemus_1_1_solution" ],
      [ "Solution_generation_single_level", "dc/dba/classfemus_1_1_solution__generation__single__level.html", "dc/dba/classfemus_1_1_solution__generation__single__level" ],
      [ "sparseGrid", "d5/dc3/classfemus_1_1sparse_grid.html", "d5/dc3/classfemus_1_1sparse_grid" ],
      [ "SparseMatrix", "d3/d61/classfemus_1_1_sparse_matrix.html", "d3/d61/classfemus_1_1_sparse_matrix" ],
      [ "System", "d5/dc7/classfemus_1_1_system.html", "d5/dc7/classfemus_1_1_system" ],
      [ "SystemTwo", "dd/d68/classfemus_1_1_system_two.html", "dd/d68/classfemus_1_1_system_two" ],
      [ "tet0", "da/d8f/classfemus_1_1tet0.html", "da/d8f/classfemus_1_1tet0" ],
      [ "tet_const", "d2/d3b/classfemus_1_1tet__const.html", "d2/d3b/classfemus_1_1tet__const" ],
      [ "tet_gauss", "d3/d95/classfemus_1_1tet__gauss.html", "d3/d95/classfemus_1_1tet__gauss" ],
      [ "tet_lag", "da/de4/classfemus_1_1tet__lag.html", "da/de4/classfemus_1_1tet__lag" ],
      [ "TetBiquadratic", "d6/d0e/classfemus_1_1_tet_biquadratic.html", "d6/d0e/classfemus_1_1_tet_biquadratic" ],
      [ "TetLinear", "d6/d10/classfemus_1_1_tet_linear.html", "d6/d10/classfemus_1_1_tet_linear" ],
      [ "tetpwLinear", "d4/da7/classfemus_1_1tetpw_linear.html", "d4/da7/classfemus_1_1tetpw_linear" ],
      [ "TetQuadratic", "d3/d1a/classfemus_1_1_tet_quadratic.html", "d3/d1a/classfemus_1_1_tet_quadratic" ],
      [ "TimeLoop", "d4/d4d/classfemus_1_1_time_loop.html", "d4/d4d/classfemus_1_1_time_loop" ],
      [ "TransientSystem", "da/d5b/classfemus_1_1_transient_system.html", "da/d5b/classfemus_1_1_transient_system" ],
      [ "tri0", "d1/d8f/classfemus_1_1tri0.html", "d1/d8f/classfemus_1_1tri0" ],
      [ "tri_const", "d1/dc4/classfemus_1_1tri__const.html", "d1/dc4/classfemus_1_1tri__const" ],
      [ "tri_gauss", "d5/d6f/classfemus_1_1tri__gauss.html", "d5/d6f/classfemus_1_1tri__gauss" ],
      [ "tri_lag", "d2/d57/classfemus_1_1tri__lag.html", "d2/d57/classfemus_1_1tri__lag" ],
      [ "TriBiquadratic", "d4/dff/classfemus_1_1_tri_biquadratic.html", "d4/dff/classfemus_1_1_tri_biquadratic" ],
      [ "TriLinear", "da/d01/classfemus_1_1_tri_linear.html", "da/d01/classfemus_1_1_tri_linear" ],
      [ "tripwLinear", "db/d3b/classfemus_1_1tripw_linear.html", "db/d3b/classfemus_1_1tripw_linear" ],
      [ "TriQuadratic", "dd/dec/classfemus_1_1_tri_quadratic.html", "dd/dec/classfemus_1_1_tri_quadratic" ],
      [ "Unknown", "d8/dea/namespacefemus.html#d3/d77/classfemus_1_1_unknown", "d8/dea/namespacefemus_d3/d77/classfemus_1_1_unknown_dup" ],
      [ "UnknownLocal", "d6/d56/classfemus_1_1_unknown_local.html", "d6/d56/classfemus_1_1_unknown_local" ],
      [ "uq", "d6/dc3/classfemus_1_1uq.html", "d6/dc3/classfemus_1_1uq" ],
      [ "VTKWriter", "d4/d8d/classfemus_1_1_v_t_k_writer.html", "d4/d8d/classfemus_1_1_v_t_k_writer" ],
      [ "wedge0", "d4/dfd/classfemus_1_1wedge0.html", "d4/dfd/classfemus_1_1wedge0" ],
      [ "wedge_const", "df/d36/classfemus_1_1wedge__const.html", "df/d36/classfemus_1_1wedge__const" ],
      [ "wedge_gauss", "d9/d65/classfemus_1_1wedge__gauss.html", "d9/d65/classfemus_1_1wedge__gauss" ],
      [ "wedge_lag", "d3/db2/classfemus_1_1wedge__lag.html", "d3/db2/classfemus_1_1wedge__lag" ],
      [ "WedgeBiquadratic", "db/d4b/classfemus_1_1_wedge_biquadratic.html", "db/d4b/classfemus_1_1_wedge_biquadratic" ],
      [ "WedgeLinear", "d9/d6b/classfemus_1_1_wedge_linear.html", "d9/d6b/classfemus_1_1_wedge_linear" ],
      [ "wedgepwLinear", "d6/df2/classfemus_1_1wedgepw_linear.html", "d6/df2/classfemus_1_1wedgepw_linear" ],
      [ "WedgeQuadratic", "d6/d9f/classfemus_1_1_wedge_quadratic.html", "d6/d9f/classfemus_1_1_wedge_quadratic" ],
      [ "Writer", "d8/dab/classfemus_1_1_writer.html", "d8/dab/classfemus_1_1_writer" ]
    ] ],
    [ "array", "d2/d41/classarray.html", "d2/d41/classarray" ],
    [ "GMPM", "d7/dfa/class_g_m_p_m.html", "d7/dfa/class_g_m_p_m" ],
    [ "MagnFieldExtLagMult", "d8/d57/class_magn_field_ext_lag_mult.html", "d8/d57/class_magn_field_ext_lag_mult" ],
    [ "MagnFieldExtX", "d2/dd7/class_magn_field_ext_x.html", "d2/dd7/class_magn_field_ext_x" ],
    [ "MagnFieldExtY", "d0/d3e/class_magn_field_ext_y.html", "d0/d3e/class_magn_field_ext_y" ],
    [ "MagnFieldExtZ", "d9/d9f/class_magn_field_ext_z.html", "d9/d9f/class_magn_field_ext_z" ],
    [ "MagnFieldHomAdjX", "d2/d97/class_magn_field_hom_adj_x.html", "d2/d97/class_magn_field_hom_adj_x" ],
    [ "MagnFieldHomAdjY", "d9/d53/class_magn_field_hom_adj_y.html", "d9/d53/class_magn_field_hom_adj_y" ],
    [ "MagnFieldHomAdjZ", "df/db6/class_magn_field_hom_adj_z.html", "df/db6/class_magn_field_hom_adj_z" ],
    [ "MagnFieldHomLagMult", "d4/dfa/class_magn_field_hom_lag_mult.html", "d4/dfa/class_magn_field_hom_lag_mult" ],
    [ "MagnFieldHomLagMultAdj", "d3/d9e/class_magn_field_hom_lag_mult_adj.html", "d3/d9e/class_magn_field_hom_lag_mult_adj" ],
    [ "MagnFieldHomX", "d6/d8f/class_magn_field_hom_x.html", "d6/d8f/class_magn_field_hom_x" ],
    [ "MagnFieldHomY", "dc/d96/class_magn_field_hom_y.html", "dc/d96/class_magn_field_hom_y" ],
    [ "MagnFieldHomZ", "db/d57/class_magn_field_hom_z.html", "db/d57/class_magn_field_hom_z" ],
    [ "Pressure", "d2/da5/class_pressure.html", "d2/da5/class_pressure" ],
    [ "PressureAdj", "d4/d47/class_pressure_adj.html", "d4/d47/class_pressure_adj" ],
    [ "Singularity", "da/d4b/class_singularity.html", "da/d4b/class_singularity" ],
    [ "Solution_generation_1", "db/d43/class_solution__generation__1.html", "db/d43/class_solution__generation__1" ],
    [ "Sphere", "d3/d62/class_sphere.html", "d3/d62/class_sphere" ],
    [ "Stokes", "d7/d84/_p_c_field_split_2ex6_2ex6_8cpp.html#dd/dbe/struct_stokes", "d7/d84/_p_c_field_split_2ex6_2ex6_8cpp_dd/dbe/struct_stokes" ],
    [ "TempAdj", "df/dff/class_temp_adj.html", "df/dff/class_temp_adj" ],
    [ "Temperature", "d0/dff/class_temperature.html", "d0/dff/class_temperature" ],
    [ "TempLift", "d1/dd8/class_temp_lift.html", "d1/dd8/class_temp_lift" ],
    [ "VelocityAdjX", "d6/dd7/class_velocity_adj_x.html", "d6/dd7/class_velocity_adj_x" ],
    [ "VelocityAdjY", "dc/d68/class_velocity_adj_y.html", "dc/d68/class_velocity_adj_y" ],
    [ "VelocityAdjZ", "d4/d40/class_velocity_adj_z.html", "d4/d40/class_velocity_adj_z" ],
    [ "VelocityX", "d7/d43/class_velocity_x.html", "d7/d43/class_velocity_x" ],
    [ "VelocityY", "d5/dcb/class_velocity_y.html", "d5/dcb/class_velocity_y" ],
    [ "VelocityZ", "de/d74/class_velocity_z.html", "de/d74/class_velocity_z" ],
    [ "WindowFunction", "d5/d25/class_window_function.html", "d5/d25/class_window_function" ],
    [ "Zero", "da/d2c/class_zero.html", "da/d2c/class_zero" ]
];