var classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___two =
[
    [ "_face_with_extremes_index", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___one___two.html#a6045a85d7dce83aabb61ff034ac5a75d", null ]
];