var classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two =
[
    [ "_face_with_extremes_index", "classfemus_1_1ctrl_1_1boundary__control__between__extreme_1_1square_1_1_list__of___gamma__control__faces___four___two.html#a7c5aca74fc545b4fffca4981d93b7c3a", null ]
];