var dir_87650b74f7e94423589f035fd108b41e =
[
    [ "00_poisson_eqn_with_all_dirichlet_bc_AD_or_nonAD_separate.hpp", "d0/df1/00__poisson__eqn__with__all__dirichlet__bc___a_d__or__non_a_d__separate_8hpp.html", "d0/df1/00__poisson__eqn__with__all__dirichlet__bc___a_d__or__non_a_d__separate_8hpp" ],
    [ "00_poisson_eqn_with_all_dirichlet_bc_AD_or_nonAD_switch.hpp", "dc/d43/00__poisson__eqn__with__all__dirichlet__bc___a_d__or__non_a_d__switch_8hpp.html", "dc/d43/00__poisson__eqn__with__all__dirichlet__bc___a_d__or__non_a_d__switch_8hpp" ],
    [ "00_poisson_eqn_with_dirichlet_or_neumann_bc.hpp", "d6/d91/00__poisson__eqn__with__dirichlet__or__neumann__bc_8hpp.html", "d6/d91/00__poisson__eqn__with__dirichlet__or__neumann__bc_8hpp" ],
    [ "00_system_specifics.hpp", "d6/d5e/00__system__specifics_8hpp.html", "d6/d5e/00__system__specifics_8hpp" ],
    [ "01_biharmonic_coupled.hpp", "d9/dcb/01__biharmonic__coupled_8hpp.html", "d9/dcb/01__biharmonic__coupled_8hpp" ],
    [ "03_navier_stokes.hpp", "d7/dce/03__navier__stokes_8hpp.html", "d7/dce/03__navier__stokes_8hpp" ],
    [ "04_boussinesq.hpp", "d3/d5c/04__boussinesq_8hpp.html", "d3/d5c/04__boussinesq_8hpp" ],
    [ "Assemble_jacobian.cpp", "d5/d88/_assemble__jacobian_8cpp.html", null ],
    [ "Assemble_jacobian.hpp", "d0/db7/_assemble__jacobian_8hpp.html", "d0/db7/_assemble__jacobian_8hpp" ],
    [ "Assemble_unknown.cpp", "de/dc9/_assemble__unknown_8cpp.html", null ],
    [ "Assemble_unknown.hpp", "d4/d78/_assemble__unknown_8hpp.html", "d4/d78/_assemble__unknown_8hpp" ],
    [ "Assemble_unknown_jacres.hpp", "d8/d3e/_assemble__unknown__jacres_8hpp.html", "d8/d3e/_assemble__unknown__jacres_8hpp" ],
    [ "Assemble_useful_functions.hpp", "db/d2c/_assemble__useful__functions_8hpp.html", "db/d2c/_assemble__useful__functions_8hpp" ],
    [ "BoundaryConditions.cpp", "db/d8b/_boundary_conditions_8cpp.html", "db/d8b/_boundary_conditions_8cpp" ],
    [ "BoundaryConditions.hpp", "da/d45/_boundary_conditions_8hpp.html", "da/d45/_boundary_conditions_8hpp" ],
    [ "CurrentElem.cpp", "db/dc1/_current_elem_8cpp.html", null ],
    [ "CurrentElem.hpp", "dc/dbc/_current_elem_8hpp.html", "dc/dbc/_current_elem_8hpp" ],
    [ "CurrentQuantity.cpp", "df/d38/_current_quantity_8cpp.html", null ],
    [ "CurrentQuantity.hpp", "d2/d49/_current_quantity_8hpp.html", "d2/d49/_current_quantity_8hpp" ],
    [ "DofMap.cpp", "de/dea/_dof_map_8cpp.html", null ],
    [ "DofMap.hpp", "d9/da3/_dof_map_8hpp.html", "d9/da3/_dof_map_8hpp" ],
    [ "Quantity.cpp", "d7/d30/_quantity_8cpp.html", null ],
    [ "Quantity.hpp", "d2/d5f/_quantity_8hpp.html", "d2/d5f/_quantity_8hpp" ],
    [ "SystemTwo.cpp", "d2/dd1/_system_two_8cpp.html", null ],
    [ "SystemTwo.hpp", "de/da5/_system_two_8hpp.html", "de/da5/_system_two_8hpp" ],
    [ "TimeLoop.cpp", "d3/df0/_time_loop_8cpp.html", null ],
    [ "TimeLoop.hpp", "d9/d9f/_time_loop_8hpp.html", "d9/d9f/_time_loop_8hpp" ]
];