var namespace_domains_1_1prism__annular__base__along__z__with__base__centered__at__0__by__0 =
[
    [ "Function_Zero_on_boundary_1", "d3/d00/class_domains_1_1prism__annular__base__along__z__with__base__centered__at__0__by__0_1_1_function___zero__on__boundary__1.html", "d3/d00/class_domains_1_1prism__annular__base__along__z__with__base__centered__at__0__by__0_1_1_function___zero__on__boundary__1" ],
    [ "bc_all_dirichlet_homogeneous", "de/d9d/namespace_domains_1_1prism__annular__base__along__z__with__base__centered__at__0__by__0.html#a45e2f65232f203072c24ca6d9de409f9", null ]
];